/**
 * GemIInI Sovereign Platform — GLOMEt National Distribution & Engineering Partner Network
 * Grounded 100% in real verified B2B intake submissions across all Sudan states.
 * Total Verified Corporate & Engineering Partners: 40
 */

const GLOMET_PARTNERS_DATABASE = [
  {
    "id": "GLOMEt-PT-001",
    "name": "د. / م. عمر دفع الله",
    "rawName": "عمر دفع الله",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249111 *** 5577",
    "emailMasked": "O***5@gmail.com",
    "field": "مختبرات",
    "education": "فوق جامعي",
    "univ": "كلية إقرأ",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "الأحياء الدقيقة (Microbiology), التشخيص الجزيئي (Molecular)",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-002",
    "name": "د. / م. عمران محمد محمد ابراهيم",
    "rawName": "عمران محمد محمد ابراهيم",
    "entity": "شركة طبية مسجلة",
    "phoneMasked": "249912 *** 2537",
    "emailMasked": "o***5@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "كلية غرب النيل",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-003",
    "name": "شركة اسبشلست الطبية المحدودة/امدرمان",
    "rawName": "شركة اسبشلست الطبية المحدودة/امدرمان",
    "entity": "شركة اسبشلست الطبية المحدودة",
    "phoneMasked": "249919 *** 6420",
    "emailMasked": "y***7@gmail.com",
    "field": "صحة عامة",
    "education": "جامعي",
    "univ": "جامعة الزعيم الازهري /كلية الصحة العامة",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "الأحياء الدقيقة (Microbiology), أجهزة الرعاية الفورية (Point of Care Devices), المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-004",
    "name": "د. / م. اونيكس للتقنية الطبية",
    "rawName": "اونيكس للتقنية الطبية",
    "entity": "اونيكس للتقنية الطبية",
    "phoneMasked": "249912 *** 2361",
    "emailMasked": "O***n@gmail.com",
    "field": "معدات طبيه",
    "education": "فوق جامعي",
    "univ": "جامعة الجزيرة",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "أمراض الدم Hematology, الكيمياء السريرية, أجهزة الرعاية الفورية, المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-005",
    "name": "د. / م. محي الدين حامد علي برشم",
    "rawName": "محي الدين حامد علي برشم",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249910 *** 1910",
    "emailMasked": "W***7@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "كلية الطب والعلوم الصحية / جامعة غرب كردفان",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "أمراض الدم Hematology, الكيمياء السريرية, الأحياء الدقيقة, المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-006",
    "name": "د. / م. Mohamed Tariq Ali Mohamed",
    "rawName": "Mohamed Tariq Ali Mohamed",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249111 *** 2913",
    "emailMasked": "m***5@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "Student",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "أمراض الدم Hematology, الكيمياء السريرية, المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-007",
    "name": "د. / م. مصطفى عبدالعظيم الامين",
    "rawName": "مصطفى عبدالعظيم الامين",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249100 *** 7640",
    "emailMasked": "m***9@gmail.com",
    "field": "معدات طبيه",
    "education": "فوق جامعي",
    "univ": "جامعه السودان بكلاريوس هندسه طبيه",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "أمراض الدم Hematology, الكيمياء السريرية, الأحياء الدقيقة",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-008",
    "name": "د. / م. تارقت للأجهزة الطبية",
    "rawName": "تارقت للأجهزة الطبية",
    "entity": "تارقت للمستلزمات الطبية",
    "phoneMasked": "249912 *** 0708",
    "emailMasked": "T***s@gmail.com",
    "field": "مختبرات",
    "education": "فوق جامعي",
    "univ": "جامعة أم درمان الإسلامية",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "الأحياء الدقيقة, التشخيص الجزيئي (Molecular), أجهزة POCT, المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-009",
    "name": "د. / م. جيهان",
    "rawName": "جيهان",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249915 *** 7544",
    "emailMasked": "J***0@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "السودان العالميه",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-010",
    "name": "د. / م. حسب الرسول",
    "rawName": "حسب الرسول",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "201145 *** 1677",
    "emailMasked": "H***k@123.com",
    "field": "طب",
    "education": "جامعي",
    "univ": "كليات الهندسة والعلوم الطبية",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "اخرى",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-011",
    "name": "د. / م. مستشفى السكري والغدد الصماء",
    "rawName": "مستشفى السكري والغدد الصماء",
    "entity": "مستشفى السكري والغدد الصماء",
    "phoneMasked": "249999 *** 7199",
    "emailMasked": "M***2@gmail.com",
    "field": "صيدله",
    "education": "جامعي",
    "univ": "كليه اليرموك",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-012",
    "name": "د. / م. Alsidig Alyamani",
    "rawName": "Alsidig Alyamani",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249123 *** 6062",
    "emailMasked": "u***a@gmail.com",
    "field": "مختبرات",
    "education": "فوق جامعي",
    "univ": "Al-GZira university",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, التشخيص الجزيئي, أجهزة POCT",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-013",
    "name": "د. / م. Aim for medical supplylies and devices",
    "rawName": "Aim for medical supplylies and devices",
    "entity": "Aim for medical supplylies and devices",
    "phoneMasked": "249112 *** 1141",
    "emailMasked": "A***D@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "Omdurman Islamic university",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-014",
    "name": "د. / م. مجدي مضوي عوض السيد مضوي",
    "rawName": "مجدي مضوي عوض السيد مضوي",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249101 *** 6429",
    "emailMasked": "m***2@gmail.com",
    "field": "مختبرات",
    "education": "جامعي",
    "univ": "ام درمان الاسلاميه",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "المستهلكات المعمليه",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD336-PHR-AFM1-BRZ",
    "name": "د. / م. صلاح الدين الوسيله",
    "rawName": "صلاح الدين الوسيله",
    "entity": "مكتب توزيع / وكالة",
    "phoneMasked": "249990 *** 9336",
    "emailMasked": "S***6@gmail.com",
    "field": "صيدله",
    "education": "فوق جامعي",
    "univ": "كليه الخرطوم",
    "regions": "الخرطوم والولايات الآمنة",
    "equipmentFocus": "اخرى",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-016",
    "name": "د. / م. Alia Mohamed",
    "rawName": "Alia Mohamed",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249907 *** 4936",
    "emailMasked": "A***a@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "النيلين",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "أمراض الدم وصورة الدم الكاملة, الأحياء الدقيقة, التشخيص الجزيئي PCR, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC ذات 3 أجزاء الاقتصادية المدمجة الموفرة للمحاليل",
    "powerStrategy": "لايوجد",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD418-MLS-AFM1-BRZ",
    "name": "د. / م. خالد حسب الرسول محمد الأمين حمد",
    "rawName": "خالد حسب الرسول محمد الأمين حمد",
    "entity": "شركة افينيو الطبية",
    "phoneMasked": "249912 *** 2418",
    "emailMasked": "K***a@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة أم درمان الأهلية",
    "regions": "ولاية البحر الأحمر (بورتسودان), ولاية نهر النيل, ولاية الجزيرة, ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, أجهزة POCT",
    "cbcFocus": "أنظمة CBC ذات 3 أجزاء (Mindray, Boule Medonic)",
    "powerStrategy": "استيراد أجهزه بها إمكانيه حفظ طاقة او بطاريات",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-018",
    "name": "د. / م. Hussein Mohammed Hamid Mohammed",
    "rawName": "Hussein Mohammed Hamid Mohammed",
    "entity": "نمر الفروع للمستهلكات والمستلزمات الطبية",
    "phoneMasked": "249961 *** 6533",
    "emailMasked": "L***n@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة العلوم والتقانة",
    "regions": "ولاية الجزيرة, ولاية الخرطوم",
    "equipmentFocus": "",
    "cbcFocus": "أجهزة ومستلزمات قياس السكر والسيولة المحمولة (Roche CoaguChek, GeneXpert)",
    "powerStrategy": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, غازات الدم Electrolytes",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-019",
    "name": "د. / م. ابرار غالب محمد",
    "rawName": "ابرار غالب محمد",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249914 *** 3671",
    "emailMasked": "a***2@gmail.com",
    "field": "الصيدلة والعلوم الدوائية والتسويق الدوائي",
    "education": "بكالوريوس / جامعي",
    "univ": "الاسلاميه",
    "regions": "ولاية البحر الأحمر (بورتسودان), ولاية الخرطوم",
    "equipmentFocus": "",
    "cbcFocus": "أجهزة ومستلزمات قياس السكر والسيولة المحمولة",
    "powerStrategy": "مستهلكات المعامل",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD475-MLS-AFM1-BRZ",
    "name": "د. / م. محمد عبدالرؤف احمد",
    "rawName": "محمد عبدالرؤف احمد",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249969 *** 2475",
    "emailMasked": "m***2@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "كلية زمزم الجامعية",
    "regions": "ولاية الجزيرة (ود مدني / المناقل)",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC 3-part (Mindray, Boule, Genrui)",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "من 2,000 إلى 5,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-021",
    "name": "د. / م. أحمد عباس إبراهيم ضوالبيت",
    "rawName": "أحمد عباس إبراهيم ضوالبيت",
    "entity": "توكيلات بيين للاجهزة والمعدات الطبية",
    "phoneMasked": "249910 *** 9697",
    "emailMasked": "A***6@gmail.com",
    "field": "الصيدلة والعلوم الدوائية والتسويق الدوائي",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة العلوم والتقانة",
    "regions": "ولاية الجزيرة, ولاية سنار, ولاية الخرطوم",
    "equipmentFocus": "الكيمياء السريرية, أجهزة POCT, مستهلكات المعامل, أجهزة ICU",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "من 5,000 إلى 15,000 دولار شهرياً",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-022",
    "name": "د. / م. وليد احمد حامد محمد علي",
    "rawName": "وليد احمد حامد محمد علي",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249915 *** 9993",
    "emailMasked": "W***2@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "كلية غرب النيل",
    "regions": "ولاية الجزيرة (ود مدني / المناقل)",
    "equipmentFocus": "أمراض الدم, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Sysmex XN, Mindray BC-6000)",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "من 2,000 إلى 5,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-023",
    "name": "د. / م. افاق ادم محمد ابكر",
    "rawName": "افاق ادم محمد ابكر",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249967 *** 1107",
    "emailMasked": "h***2@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة الجزيرة /البيان",
    "regions": "ولاية سنار",
    "equipmentFocus": "مستهلكات المعامل العامة وسحب الدم",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-024",
    "name": "د. / م. صالح جارالنبي صديق عبد الكريم",
    "rawName": "صالح جارالنبي صديق عبد الكريم",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249906 *** 7079",
    "emailMasked": "S***5@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "بكالوريوس / جامعي",
    "univ": "كلية النور للعلوم والتكنولوجيا",
    "regions": "ولايات دارفور (الفاشر / نيالا / الجنينة)",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, أجهزة POCT, مستهلكات المعامل, أجهزة ICU",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Horiba Yumizen, Sysmex XN, Mindray)",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-025",
    "name": "د. / م. الطيب أبوالقاسم البارودي",
    "rawName": "الطيب أبوالقاسم البارودي",
    "entity": "البارودي الطبية",
    "phoneMasked": "249116 *** 9008",
    "emailMasked": "a***d@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة الجزيرة المستوى الثالث",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "أمراض الدم, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "تضرر اللوحات الإلكترونية للأجهزة",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD431-ENG-AFM1-BRZ",
    "name": "د. / م. عسجد حمدالنيل محمد يوسف",
    "rawName": "عسجد حمدالنيل محمد يوسف",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249962 *** 4431",
    "emailMasked": "a***l@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة العلوم و التقانه",
    "regions": "ولاية الجزيرة, ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, التشخيص الجزيئي PCR, مستهلكات المعامل, أجهزة الأشعة والأسنان",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Horiba Yumizen, Sysmex, Mindray)",
    "powerStrategy": "الأجهزة متوفرة في الشركة",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-027",
    "name": "د. / م. المنذر ايوب عمر النعيمة",
    "rawName": "المنذر ايوب عمر النعيمة",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249116 *** 9528",
    "emailMasked": "m***3@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "دبلوم تقني / فني",
    "univ": "جامعة السودان للعلوم والتكنلوجيا",
    "regions": "ولاية القضارف, ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, التشخيص الجزيئي PCR, غازات الدم, مستلزمات الأسنان",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Horiba, Sysmex XN, Mindray)",
    "powerStrategy": "مولدات خاصة (Generator) وأنظمة حماية ومثبتات جهد",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-028",
    "name": "د. / م. عبدالوهاب عبدالله علي",
    "rawName": "عبدالوهاب عبدالله علي",
    "entity": "ستارت للأجهزة والمعدات الطبية",
    "phoneMasked": "249120 *** 8770",
    "emailMasked": "S***s@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "ماجستير علوم (MSc)",
    "univ": "جامعة ام درمان الإسلامية",
    "regions": "ولاية نهر النيل, الولاية الشمالية, ولاية النيل الأبيض, ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, التشخيص الجزيئي PCR, أجهزة POCT, أجهزة ICU",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "مولدات خاصة مع أنظمة حماية ومثبتات جهد",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "من 5,000 إلى 15,000 دولار شهرياً",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-029",
    "name": "د. / م. Abdalaliem faiz",
    "rawName": "Abdalaliem faiz",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249923 *** 4918",
    "emailMasked": "b***y@gmail.com",
    "field": "معدات طبيه",
    "education": "دبلوم تقني / فني",
    "univ": "مارستها ميدانياً",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "مستهلكات المعامل, أجهزة الأشعة التشخيصية والموجات الصوتية",
    "cbcFocus": "لا أعمل في خطوط صورة الدم حالياً",
    "powerStrategy": "أنظمة التخزين المؤقت UPS",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-030",
    "name": "د. / م. حازم عمر بحر",
    "rawName": "حازم عمر بحر",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249992 *** 7404",
    "emailMasked": "h***1@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة المستقبل",
    "regions": "ولاية البحر الأحمر (بورتسودان / سواكن)",
    "equipmentFocus": "أمراض الدم, الأحياء الدقيقة, أجهزة POCT, مستهلكات المعامل, أجهزة الأشعة والأسنان",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Sysmex XN, Mindray BC-6000)",
    "powerStrategy": "تضرر اللوحات الإلكترونية للأجهزة",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD004-SCI-MTC1-BRZ",
    "name": "د. / م. مؤيد احمد حامد قمر الدين",
    "rawName": "مؤيد احمد حامد قمر الدين",
    "entity": "نبض الطبية",
    "phoneMasked": "249905 *** 8004",
    "emailMasked": "m***0@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "ام درمان الإسلامية",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "أمراض الدم, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Sysmex XN, Mindray)",
    "powerStrategy": "تضرر اللوحات الإلكترونية للأجهزة",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "من 2,000 إلى 5,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD594-SCI-AFM1-BRZ",
    "name": "د. / م. Moram hashim khider abdalla",
    "rawName": "Moram hashim khider abdalla",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249119 *** 8594",
    "emailMasked": "m***0@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "دبلوم عالي / فوق جامعي",
    "univ": "كلية اليرموك",
    "regions": "الولاية الشمالية (دنقلا / مروي / وادي حلفا), ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, مستهلكات المعامل, غازات الدم",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "مولدات خاصة مع أنظمة حماية ومثبتات جهد",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD125-DNT-AFM1-BRZ",
    "name": "د. / م. Mohammed Abd ALmohsin Mohammed babkir",
    "rawName": "Mohammed Abd ALmohsin Mohammed babkir",
    "entity": "Dar med heath & education",
    "phoneMasked": "249968 *** 5861",
    "emailMasked": "m***9@gmail.com",
    "field": "علوم طب وجراحة الأسنان ومستلزماتها",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة الرازي _ كلية طب وجراحة الفم و الأسنان",
    "regions": "الولاية الشمالية (دنقلا / مروي), ولاية نهر النيل (شندي / عطبرة), ولاية الخرطوم",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, أجهزة POCT, أجهزة الأشعة, مستلزمات الأسنان",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "أنظمة التخزين المؤقت UPS للأجهزة الصغيرة",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD665-SCI-MTC1-BRZ",
    "name": "د. / م. مؤيد حيدر بطران إدريس",
    "rawName": "مؤيد حيدر بطران إدريس",
    "entity": "شركة الشهباء للأدوية و المعدات الطبية",
    "phoneMasked": "249997 *** 2924",
    "emailMasked": "M***9@gmail.com",
    "field": "الطب البشري والجراحة",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة الإمام المهدي _ كلية الطب والجراحة",
    "regions": "ولاية النيل الأبيض (كوشتي / ربك / القطينة / الدويم)",
    "equipmentFocus": "أمراض الدم, مستهلكات المعامل",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD288-MLS-AFM1-BRZ",
    "name": "د. / م. عبدالحليم مكي حسن محمد علي",
    "rawName": "عبدالحليم مكي حسن محمد علي",
    "entity": "مستوصف الشفاء الطبي",
    "phoneMasked": "249917 *** 8288",
    "emailMasked": "A***i@Jmil.com",
    "field": "علوم المختبرات الطبية",
    "education": "دبلوم تقني / فني",
    "univ": "كليه الطب والعلوم الصحيه جامعه كسلا",
    "regions": "ولاية القضارف, ولاية كسلا",
    "equipmentFocus": "مستهلكات المعامل العامة وسحب الدم",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "مولدات خاصة مع أنظمة حماية ومثبتات جهد",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD240-ENG-AFM1-BRZ",
    "name": "د. / م. احمد حسن يوسف عمر",
    "rawName": "احمد حسن يوسف عمر",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249907 *** 2240",
    "emailMasked": "a***9@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة الزعيم الازهري",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD533-MLS-AFM1-BRZ",
    "name": "د. / م. Hussein Mohammed Hamid Mohammed",
    "rawName": "Hussein Mohammed Hamid Mohammed",
    "entity": "نمر الفروع للمستهلكات والمستلزمات الطبية",
    "phoneMasked": "249961 *** 6533",
    "emailMasked": "l***n@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "دبلوم عالي / فوق جامعي",
    "univ": "جامعة العلوم والتقانة",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة, غازات الدم, مستلزمات الأسنان",
    "cbcFocus": "أنظمة CBC 3-part و 5-part (Sysmex XN, Mindray)",
    "powerStrategy": "أنظمة التخزين المؤقت UPS للأجهزة الصغيرة",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "من 2,000 إلى 5,000 دولار شهرياً",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-038",
    "name": "د. / م. وائل فتح الرحمن",
    "rawName": "وائل فتح الرحمن",
    "entity": "ورشة صابرين للاثاثات الطبية",
    "phoneMasked": "249100 *** 5380",
    "emailMasked": "w***9@gmail.com",
    "field": "أخرى",
    "education": "بكالوريوس / جامعي",
    "univ": "الكلية الاردنية السودانية للعلوم والتكنولوجيا",
    "regions": "ولاية الخرطوم (أم درمان / بحري / الخرطوم)",
    "equipmentFocus": "مستلزمات طب الأسنان والأثاثات الطبية",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "مولدات خاصة مع أنظمة حماية ومثبتات جهد",
    "bufferStock": "توريد فوري أسبوعي Just-in-Time",
    "monthlyCapacity": "أقل من 2,000 دولار شهرياً",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-039",
    "name": "د. / م. أشرف عماد الدين هاشم موسي",
    "rawName": "أشرف عماد الدين هاشم موسي",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "249911 *** 9697",
    "emailMasked": "a***n@gmail.com",
    "field": "هندسة طبية حيوية / صيانة معدات طبية",
    "education": "دبلوم تقني / فني",
    "univ": "جامعة الجزيرة",
    "regions": "ولاية الجزيرة (ود مدني / المناقل)",
    "equipmentFocus": "أجهزة الرعاية الحرجة والعناية المكثفة والتخدير (ICU)",
    "cbcFocus": "أنظمة CBC 5-part (Horiba Yumizen, Sysmex, Mindray)",
    "powerStrategy": "أنظمة التخزين المؤقت UPS للأجهزة الصغيرة",
    "bufferStock": "مخزون يكفي لتغطية شهر واحد تشغيلي",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-040",
    "name": "د. / م. Dfaalla altom dfaalla",
    "rawName": "Dfaalla altom dfaalla",
    "entity": "وكيل / مندوب مستقل",
    "phoneMasked": "002499 *** 3935",
    "emailMasked": "D***6@gmail.com",
    "field": "علوم المختبرات الطبية",
    "education": "بكالوريوس / جامعي",
    "univ": "جامعة امدرمان الاسلامية",
    "regions": "ولاية النيل الأزرق (الدمازين)",
    "equipmentFocus": "أمراض الدم, الكيمياء السريرية, الأحياء الدقيقة",
    "cbcFocus": "أنظمة CBC 3-part",
    "powerStrategy": "طاقة شمسية وبطاريات",
    "bufferStock": "مخزون استراتيجي من شهرين إلى 3 أشهر",
    "monthlyCapacity": "لا استطيع التقدير",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  }
];

const GLOMET_PARTNERS_METRICS = {
  totalPartners: 40,
  statesCovered: 10,
  biomedicalEngineeringCount: 11,
  corporateEntitiesCount: 6,
  independentBrokersCount: 22
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GLOMET_PARTNERS_DATABASE, GLOMET_PARTNERS_METRICS };
}
