/**
 * GemIInI SudaGene Platform â€” GLOMEt National Distribution & Engineering Partner Network
 * Grounded 100% in real verified B2B intake submissions across all Sudan states.
 * Total Verified Corporate & Engineering Partners: 40
 */

const GLOMET_PARTNERS_DATABASE = [
  {
    "id": "GLOMEt-PT-001",
    "name": "Ø¯. / Ù…. Ø¹Ù…Ø± Ø¯ÙØ¹ Ø§Ù„Ù„Ù‡",
    "rawName": "Ø¹Ù…Ø± Ø¯ÙØ¹ Ø§Ù„Ù„Ù‡",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249111 *** 5577",
    "emailMasked": "O***5@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© Ø¥Ù‚Ø±Ø£",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø© (Microbiology), Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ (Molecular)",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-002",
    "name": "Ø¯. / Ù…. Ø¹Ù…Ø±Ø§Ù† Ù…Ø­Ù…Ø¯ Ù…Ø­Ù…Ø¯ Ø§Ø¨Ø±Ø§Ù‡ÙŠÙ…",
    "rawName": "Ø¹Ù…Ø±Ø§Ù† Ù…Ø­Ù…Ø¯ Ù…Ø­Ù…Ø¯ Ø§Ø¨Ø±Ø§Ù‡ÙŠÙ…",
    "entity": "Ø´Ø±ÙƒØ© Ø·Ø¨ÙŠØ© Ù…Ø³Ø¬Ù„Ø©",
    "phoneMasked": "249912 *** 2537",
    "emailMasked": "o***5@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© ØºØ±Ø¨ Ø§Ù„Ù†ÙŠÙ„",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-003",
    "name": "Ø´Ø±ÙƒØ© Ø§Ø³Ø¨Ø´Ù„Ø³Øª Ø§Ù„Ø·Ø¨ÙŠØ© Ø§Ù„Ù…Ø­Ø¯ÙˆØ¯Ø©/Ø§Ù…Ø¯Ø±Ù…Ø§Ù†",
    "rawName": "Ø´Ø±ÙƒØ© Ø§Ø³Ø¨Ø´Ù„Ø³Øª Ø§Ù„Ø·Ø¨ÙŠØ© Ø§Ù„Ù…Ø­Ø¯ÙˆØ¯Ø©/Ø§Ù…Ø¯Ø±Ù…Ø§Ù†",
    "entity": "Ø´Ø±ÙƒØ© Ø§Ø³Ø¨Ø´Ù„Ø³Øª Ø§Ù„Ø·Ø¨ÙŠØ© Ø§Ù„Ù…Ø­Ø¯ÙˆØ¯Ø©",
    "phoneMasked": "249919 *** 6420",
    "emailMasked": "y***7@gmail.com",
    "field": "ØµØ­Ø© Ø¹Ø§Ù…Ø©",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø²Ø¹ÙŠÙ… Ø§Ù„Ø§Ø²Ù‡Ø±ÙŠ /ÙƒÙ„ÙŠØ© Ø§Ù„ØµØ­Ø© Ø§Ù„Ø¹Ø§Ù…Ø©",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø© (Microbiology), Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø±Ø¹Ø§ÙŠØ© Ø§Ù„ÙÙˆØ±ÙŠØ© (Point of Care Devices), Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-004",
    "name": "Ø¯. / Ù…. Ø§ÙˆÙ†ÙŠÙƒØ³ Ù„Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„Ø·Ø¨ÙŠØ©",
    "rawName": "Ø§ÙˆÙ†ÙŠÙƒØ³ Ù„Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„Ø·Ø¨ÙŠØ©",
    "entity": "Ø§ÙˆÙ†ÙŠÙƒØ³ Ù„Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249912 *** 2361",
    "emailMasked": "O***n@gmail.com",
    "field": "Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠÙ‡",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù… Hematology, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø±Ø¹Ø§ÙŠØ© Ø§Ù„ÙÙˆØ±ÙŠØ©, Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-005",
    "name": "Ø¯. / Ù…. Ù…Ø­ÙŠ Ø§Ù„Ø¯ÙŠÙ† Ø­Ø§Ù…Ø¯ Ø¹Ù„ÙŠ Ø¨Ø±Ø´Ù…",
    "rawName": "Ù…Ø­ÙŠ Ø§Ù„Ø¯ÙŠÙ† Ø­Ø§Ù…Ø¯ Ø¹Ù„ÙŠ Ø¨Ø±Ø´Ù…",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249910 *** 1910",
    "emailMasked": "W***7@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© Ø§Ù„Ø·Ø¨ ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„ØµØ­ÙŠØ© / Ø¬Ø§Ù…Ø¹Ø© ØºØ±Ø¨ ÙƒØ±Ø¯ÙØ§Ù†",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù… Hematology, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-006",
    "name": "Ø¯. / Ù…. Mohamed Tariq Ali Mohamed",
    "rawName": "Mohamed Tariq Ali Mohamed",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249111 *** 2913",
    "emailMasked": "m***5@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Student",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù… Hematology, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-007",
    "name": "Ø¯. / Ù…. Ù…ØµØ·ÙÙ‰ Ø¹Ø¨Ø¯Ø§Ù„Ø¹Ø¸ÙŠÙ… Ø§Ù„Ø§Ù…ÙŠÙ†",
    "rawName": "Ù…ØµØ·ÙÙ‰ Ø¹Ø¨Ø¯Ø§Ù„Ø¹Ø¸ÙŠÙ… Ø§Ù„Ø§Ù…ÙŠÙ†",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249100 *** 7640",
    "emailMasked": "m***9@gmail.com",
    "field": "Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠÙ‡",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ù‡ Ø§Ù„Ø³ÙˆØ¯Ø§Ù† Ø¨ÙƒÙ„Ø§Ø±ÙŠÙˆØ³ Ù‡Ù†Ø¯Ø³Ù‡ Ø·Ø¨ÙŠÙ‡",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù… Hematology, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-008",
    "name": "Ø¯. / Ù…. ØªØ§Ø±Ù‚Øª Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø·Ø¨ÙŠØ©",
    "rawName": "ØªØ§Ø±Ù‚Øª Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø·Ø¨ÙŠØ©",
    "entity": "ØªØ§Ø±Ù‚Øª Ù„Ù„Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249912 *** 0708",
    "emailMasked": "T***s@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø£Ù… Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø¥Ø³Ù„Ø§Ù…ÙŠØ©",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ (Molecular), Ø£Ø¬Ù‡Ø²Ø© POCT, Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-009",
    "name": "Ø¯. / Ù…. Ø¬ÙŠÙ‡Ø§Ù†",
    "rawName": "Ø¬ÙŠÙ‡Ø§Ù†",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249915 *** 7544",
    "emailMasked": "J***0@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù„Ø³ÙˆØ¯Ø§Ù† Ø§Ù„Ø¹Ø§Ù„Ù…ÙŠÙ‡",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-010",
    "name": "Ø¯. / Ù…. Ø­Ø³Ø¨ Ø§Ù„Ø±Ø³ÙˆÙ„",
    "rawName": "Ø­Ø³Ø¨ Ø§Ù„Ø±Ø³ÙˆÙ„",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "201145 *** 1677",
    "emailMasked": "H***k@123.com",
    "field": "Ø·Ø¨",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ§Øª Ø§Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø·Ø¨ÙŠØ©",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ø®Ø±Ù‰",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-011",
    "name": "Ø¯. / Ù…. Ù…Ø³ØªØ´ÙÙ‰ Ø§Ù„Ø³ÙƒØ±ÙŠ ÙˆØ§Ù„ØºØ¯Ø¯ Ø§Ù„ØµÙ…Ø§Ø¡",
    "rawName": "Ù…Ø³ØªØ´ÙÙ‰ Ø§Ù„Ø³ÙƒØ±ÙŠ ÙˆØ§Ù„ØºØ¯Ø¯ Ø§Ù„ØµÙ…Ø§Ø¡",
    "entity": "Ù…Ø³ØªØ´ÙÙ‰ Ø§Ù„Ø³ÙƒØ±ÙŠ ÙˆØ§Ù„ØºØ¯Ø¯ Ø§Ù„ØµÙ…Ø§Ø¡",
    "phoneMasked": "249999 *** 7199",
    "emailMasked": "M***2@gmail.com",
    "field": "ØµÙŠØ¯Ù„Ù‡",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠÙ‡ Ø§Ù„ÙŠØ±Ù…ÙˆÙƒ",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-012",
    "name": "Ø¯. / Ù…. Alsidig Alyamani",
    "rawName": "Alsidig Alyamani",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249123 *** 6062",
    "emailMasked": "u***a@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Al-GZira university",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ, Ø£Ø¬Ù‡Ø²Ø© POCT",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-013",
    "name": "Ø¯. / Ù…. Aim for medical supplylies and devices",
    "rawName": "Aim for medical supplylies and devices",
    "entity": "Aim for medical supplylies and devices",
    "phoneMasked": "249112 *** 1141",
    "emailMasked": "A***D@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Omdurman Islamic university",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-014",
    "name": "Ø¯. / Ù…. Ù…Ø¬Ø¯ÙŠ Ù…Ø¶ÙˆÙŠ Ø¹ÙˆØ¶ Ø§Ù„Ø³ÙŠØ¯ Ù…Ø¶ÙˆÙŠ",
    "rawName": "Ù…Ø¬Ø¯ÙŠ Ù…Ø¶ÙˆÙŠ Ø¹ÙˆØ¶ Ø§Ù„Ø³ÙŠØ¯ Ù…Ø¶ÙˆÙŠ",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249101 *** 6429",
    "emailMasked": "m***2@gmail.com",
    "field": "Ù…Ø®ØªØ¨Ø±Ø§Øª",
    "education": "Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù… Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø§Ø³Ù„Ø§Ù…ÙŠÙ‡",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ù…Ù„ÙŠÙ‡",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD336-PHR-AFM1-BRZ",
    "name": "Ø¯. / Ù…. ØµÙ„Ø§Ø­ Ø§Ù„Ø¯ÙŠÙ† Ø§Ù„ÙˆØ³ÙŠÙ„Ù‡",
    "rawName": "ØµÙ„Ø§Ø­ Ø§Ù„Ø¯ÙŠÙ† Ø§Ù„ÙˆØ³ÙŠÙ„Ù‡",
    "entity": "Ù…ÙƒØªØ¨ ØªÙˆØ²ÙŠØ¹ / ÙˆÙƒØ§Ù„Ø©",
    "phoneMasked": "249990 *** 9336",
    "emailMasked": "S***6@gmail.com",
    "field": "ØµÙŠØ¯Ù„Ù‡",
    "education": "ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠÙ‡ Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "regions": "Ø§Ù„Ø®Ø±Ø·ÙˆÙ… ÙˆØ§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ø¢Ù…Ù†Ø©",
    "equipmentFocus": "Ø§Ø®Ø±Ù‰",
    "cbcFocus": "",
    "powerStrategy": "",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-016",
    "name": "Ø¯. / Ù…. Alia Mohamed",
    "rawName": "Alia Mohamed",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249907 *** 4936",
    "emailMasked": "A***a@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù„Ù†ÙŠÙ„ÙŠÙ†",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù… ÙˆØµÙˆØ±Ø© Ø§Ù„Ø¯Ù… Ø§Ù„ÙƒØ§Ù…Ù„Ø©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ PCR, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC Ø°Ø§Øª 3 Ø£Ø¬Ø²Ø§Ø¡ Ø§Ù„Ø§Ù‚ØªØµØ§Ø¯ÙŠØ© Ø§Ù„Ù…Ø¯Ù…Ø¬Ø© Ø§Ù„Ù…ÙˆÙØ±Ø© Ù„Ù„Ù…Ø­Ø§Ù„ÙŠÙ„",
    "powerStrategy": "Ù„Ø§ÙŠÙˆØ¬Ø¯",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD418-MLS-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Ø®Ø§Ù„Ø¯ Ø­Ø³Ø¨ Ø§Ù„Ø±Ø³ÙˆÙ„ Ù…Ø­Ù…Ø¯ Ø§Ù„Ø£Ù…ÙŠÙ† Ø­Ù…Ø¯",
    "rawName": "Ø®Ø§Ù„Ø¯ Ø­Ø³Ø¨ Ø§Ù„Ø±Ø³ÙˆÙ„ Ù…Ø­Ù…Ø¯ Ø§Ù„Ø£Ù…ÙŠÙ† Ø­Ù…Ø¯",
    "entity": "Ø´Ø±ÙƒØ© Ø§ÙÙŠÙ†ÙŠÙˆ Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249912 *** 2418",
    "emailMasked": "K***a@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø£Ù… Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø£Ù‡Ù„ÙŠØ©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¨Ø­Ø± Ø§Ù„Ø£Ø­Ù…Ø± (Ø¨ÙˆØ±ØªØ³ÙˆØ¯Ø§Ù†), ÙˆÙ„Ø§ÙŠØ© Ù†Ù‡Ø± Ø§Ù„Ù†ÙŠÙ„, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø£Ø¬Ù‡Ø²Ø© POCT",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC Ø°Ø§Øª 3 Ø£Ø¬Ø²Ø§Ø¡ (Mindray, Boule Medonic)",
    "powerStrategy": "Ø§Ø³ØªÙŠØ±Ø§Ø¯ Ø£Ø¬Ù‡Ø²Ù‡ Ø¨Ù‡Ø§ Ø¥Ù…ÙƒØ§Ù†ÙŠÙ‡ Ø­ÙØ¸ Ø·Ø§Ù‚Ø© Ø§Ùˆ Ø¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-018",
    "name": "Ø¯. / Ù…. Hussein Mohammed Hamid Mohammed",
    "rawName": "Hussein Mohammed Hamid Mohammed",
    "entity": "Ù†Ù…Ø± Ø§Ù„ÙØ±ÙˆØ¹ Ù„Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª ÙˆØ§Ù„Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249961 *** 6533",
    "emailMasked": "L***n@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙ‚Ø§Ù†Ø©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "",
    "cbcFocus": "Ø£Ø¬Ù‡Ø²Ø© ÙˆÙ…Ø³ØªÙ„Ø²Ù…Ø§Øª Ù‚ÙŠØ§Ø³ Ø§Ù„Ø³ÙƒØ± ÙˆØ§Ù„Ø³ÙŠÙˆÙ„Ø© Ø§Ù„Ù…Ø­Ù…ÙˆÙ„Ø© (Roche CoaguChek, GeneXpert)",
    "powerStrategy": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, ØºØ§Ø²Ø§Øª Ø§Ù„Ø¯Ù… Electrolytes",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-019",
    "name": "Ø¯. / Ù…. Ø§Ø¨Ø±Ø§Ø± ØºØ§Ù„Ø¨ Ù…Ø­Ù…Ø¯",
    "rawName": "Ø§Ø¨Ø±Ø§Ø± ØºØ§Ù„Ø¨ Ù…Ø­Ù…Ø¯",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249914 *** 3671",
    "emailMasked": "a***2@gmail.com",
    "field": "Ø§Ù„ØµÙŠØ¯Ù„Ø© ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø¯ÙˆØ§Ø¦ÙŠØ© ÙˆØ§Ù„ØªØ³ÙˆÙŠÙ‚ Ø§Ù„Ø¯ÙˆØ§Ø¦ÙŠ",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù„Ø§Ø³Ù„Ø§Ù…ÙŠÙ‡",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¨Ø­Ø± Ø§Ù„Ø£Ø­Ù…Ø± (Ø¨ÙˆØ±ØªØ³ÙˆØ¯Ø§Ù†), ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "",
    "cbcFocus": "Ø£Ø¬Ù‡Ø²Ø© ÙˆÙ…Ø³ØªÙ„Ø²Ù…Ø§Øª Ù‚ÙŠØ§Ø³ Ø§Ù„Ø³ÙƒØ± ÙˆØ§Ù„Ø³ÙŠÙˆÙ„Ø© Ø§Ù„Ù…Ø­Ù…ÙˆÙ„Ø©",
    "powerStrategy": "Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "bufferStock": "",
    "monthlyCapacity": "",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD475-MLS-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Ù…Ø­Ù…Ø¯ Ø¹Ø¨Ø¯Ø§Ù„Ø±Ø¤Ù Ø§Ø­Ù…Ø¯",
    "rawName": "Ù…Ø­Ù…Ø¯ Ø¹Ø¨Ø¯Ø§Ù„Ø±Ø¤Ù Ø§Ø­Ù…Ø¯",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249969 *** 2475",
    "emailMasked": "m***2@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© Ø²Ù…Ø²Ù… Ø§Ù„Ø¬Ø§Ù…Ø¹ÙŠØ©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© (ÙˆØ¯ Ù…Ø¯Ù†ÙŠ / Ø§Ù„Ù…Ù†Ø§Ù‚Ù„)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part (Mindray, Boule, Genrui)",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù…Ù† 2,000 Ø¥Ù„Ù‰ 5,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-021",
    "name": "Ø¯. / Ù…. Ø£Ø­Ù…Ø¯ Ø¹Ø¨Ø§Ø³ Ø¥Ø¨Ø±Ø§Ù‡ÙŠÙ… Ø¶ÙˆØ§Ù„Ø¨ÙŠØª",
    "rawName": "Ø£Ø­Ù…Ø¯ Ø¹Ø¨Ø§Ø³ Ø¥Ø¨Ø±Ø§Ù‡ÙŠÙ… Ø¶ÙˆØ§Ù„Ø¨ÙŠØª",
    "entity": "ØªÙˆÙƒÙŠÙ„Ø§Øª Ø¨ÙŠÙŠÙ† Ù„Ù„Ø§Ø¬Ù‡Ø²Ø© ÙˆØ§Ù„Ù…Ø¹Ø¯Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249910 *** 9697",
    "emailMasked": "A***6@gmail.com",
    "field": "Ø§Ù„ØµÙŠØ¯Ù„Ø© ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø¯ÙˆØ§Ø¦ÙŠØ© ÙˆØ§Ù„ØªØ³ÙˆÙŠÙ‚ Ø§Ù„Ø¯ÙˆØ§Ø¦ÙŠ",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙ‚Ø§Ù†Ø©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©, ÙˆÙ„Ø§ÙŠØ© Ø³Ù†Ø§Ø±, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø£Ø¬Ù‡Ø²Ø© POCT, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, Ø£Ø¬Ù‡Ø²Ø© ICU",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù…Ù† 5,000 Ø¥Ù„Ù‰ 15,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-022",
    "name": "Ø¯. / Ù…. ÙˆÙ„ÙŠØ¯ Ø§Ø­Ù…Ø¯ Ø­Ø§Ù…Ø¯ Ù…Ø­Ù…Ø¯ Ø¹Ù„ÙŠ",
    "rawName": "ÙˆÙ„ÙŠØ¯ Ø§Ø­Ù…Ø¯ Ø­Ø§Ù…Ø¯ Ù…Ø­Ù…Ø¯ Ø¹Ù„ÙŠ",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249915 *** 9993",
    "emailMasked": "W***2@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© ØºØ±Ø¨ Ø§Ù„Ù†ÙŠÙ„",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© (ÙˆØ¯ Ù…Ø¯Ù†ÙŠ / Ø§Ù„Ù…Ù†Ø§Ù‚Ù„)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Sysmex XN, Mindray BC-6000)",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ù…Ù† 2,000 Ø¥Ù„Ù‰ 5,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-023",
    "name": "Ø¯. / Ù…. Ø§ÙØ§Ù‚ Ø§Ø¯Ù… Ù…Ø­Ù…Ø¯ Ø§Ø¨ÙƒØ±",
    "rawName": "Ø§ÙØ§Ù‚ Ø§Ø¯Ù… Ù…Ø­Ù…Ø¯ Ø§Ø¨ÙƒØ±",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249967 *** 1107",
    "emailMasked": "h***2@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© /Ø§Ù„Ø¨ÙŠØ§Ù†",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø³Ù†Ø§Ø±",
    "equipmentFocus": "Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„ Ø§Ù„Ø¹Ø§Ù…Ø© ÙˆØ³Ø­Ø¨ Ø§Ù„Ø¯Ù…",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-024",
    "name": "Ø¯. / Ù…. ØµØ§Ù„Ø­ Ø¬Ø§Ø±Ø§Ù„Ù†Ø¨ÙŠ ØµØ¯ÙŠÙ‚ Ø¹Ø¨Ø¯ Ø§Ù„ÙƒØ±ÙŠÙ…",
    "rawName": "ØµØ§Ù„Ø­ Ø¬Ø§Ø±Ø§Ù„Ù†Ø¨ÙŠ ØµØ¯ÙŠÙ‚ Ø¹Ø¨Ø¯ Ø§Ù„ÙƒØ±ÙŠÙ…",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249906 *** 7079",
    "emailMasked": "S***5@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© Ø§Ù„Ù†ÙˆØ± Ù„Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§",
    "regions": "ÙˆÙ„Ø§ÙŠØ§Øª Ø¯Ø§Ø±ÙÙˆØ± (Ø§Ù„ÙØ§Ø´Ø± / Ù†ÙŠØ§Ù„Ø§ / Ø§Ù„Ø¬Ù†ÙŠÙ†Ø©)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø£Ø¬Ù‡Ø²Ø© POCT, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, Ø£Ø¬Ù‡Ø²Ø© ICU",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Horiba Yumizen, Sysmex XN, Mindray)",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-025",
    "name": "Ø¯. / Ù…. Ø§Ù„Ø·ÙŠØ¨ Ø£Ø¨ÙˆØ§Ù„Ù‚Ø§Ø³Ù… Ø§Ù„Ø¨Ø§Ø±ÙˆØ¯ÙŠ",
    "rawName": "Ø§Ù„Ø·ÙŠØ¨ Ø£Ø¨ÙˆØ§Ù„Ù‚Ø§Ø³Ù… Ø§Ù„Ø¨Ø§Ø±ÙˆØ¯ÙŠ",
    "entity": "Ø§Ù„Ø¨Ø§Ø±ÙˆØ¯ÙŠ Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249116 *** 9008",
    "emailMasked": "a***d@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© Ø§Ù„Ù…Ø³ØªÙˆÙ‰ Ø§Ù„Ø«Ø§Ù„Ø«",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "ØªØ¶Ø±Ø± Ø§Ù„Ù„ÙˆØ­Ø§Øª Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ù„Ø£Ø¬Ù‡Ø²Ø©",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD431-ENG-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Ø¹Ø³Ø¬Ø¯ Ø­Ù…Ø¯Ø§Ù„Ù†ÙŠÙ„ Ù…Ø­Ù…Ø¯ ÙŠÙˆØ³Ù",
    "rawName": "Ø¹Ø³Ø¬Ø¯ Ø­Ù…Ø¯Ø§Ù„Ù†ÙŠÙ„ Ù…Ø­Ù…Ø¯ ÙŠÙˆØ³Ù",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249962 *** 4431",
    "emailMasked": "a***l@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¹Ù„ÙˆÙ… Ùˆ Ø§Ù„ØªÙ‚Ø§Ù†Ù‡",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ PCR, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø£Ø´Ø¹Ø© ÙˆØ§Ù„Ø£Ø³Ù†Ø§Ù†",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Horiba Yumizen, Sysmex, Mindray)",
    "powerStrategy": "Ø§Ù„Ø£Ø¬Ù‡Ø²Ø© Ù…ØªÙˆÙØ±Ø© ÙÙŠ Ø§Ù„Ø´Ø±ÙƒØ©",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-027",
    "name": "Ø¯. / Ù…. Ø§Ù„Ù…Ù†Ø°Ø± Ø§ÙŠÙˆØ¨ Ø¹Ù…Ø± Ø§Ù„Ù†Ø¹ÙŠÙ…Ø©",
    "rawName": "Ø§Ù„Ù…Ù†Ø°Ø± Ø§ÙŠÙˆØ¨ Ø¹Ù…Ø± Ø§Ù„Ù†Ø¹ÙŠÙ…Ø©",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249116 *** 9528",
    "emailMasked": "m***3@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… ØªÙ‚Ù†ÙŠ / ÙÙ†ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø³ÙˆØ¯Ø§Ù† Ù„Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙƒÙ†Ù„ÙˆØ¬ÙŠØ§",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ù‚Ø¶Ø§Ø±Ù, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ PCR, ØºØ§Ø²Ø§Øª Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø£Ø³Ù†Ø§Ù†",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Horiba, Sysmex XN, Mindray)",
    "powerStrategy": "Ù…ÙˆÙ„Ø¯Ø§Øª Ø®Ø§ØµØ© (Generator) ÙˆØ£Ù†Ø¸Ù…Ø© Ø­Ù…Ø§ÙŠØ© ÙˆÙ…Ø«Ø¨ØªØ§Øª Ø¬Ù‡Ø¯",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-028",
    "name": "Ø¯. / Ù…. Ø¹Ø¨Ø¯Ø§Ù„ÙˆÙ‡Ø§Ø¨ Ø¹Ø¨Ø¯Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠ",
    "rawName": "Ø¹Ø¨Ø¯Ø§Ù„ÙˆÙ‡Ø§Ø¨ Ø¹Ø¨Ø¯Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠ",
    "entity": "Ø³ØªØ§Ø±Øª Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© ÙˆØ§Ù„Ù…Ø¹Ø¯Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249120 *** 8770",
    "emailMasked": "S***s@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ù…Ø§Ø¬Ø³ØªÙŠØ± Ø¹Ù„ÙˆÙ… (MSc)",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù… Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø¥Ø³Ù„Ø§Ù…ÙŠØ©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ù†Ù‡Ø± Ø§Ù„Ù†ÙŠÙ„, Ø§Ù„ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø´Ù…Ø§Ù„ÙŠØ©, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ù†ÙŠÙ„ Ø§Ù„Ø£Ø¨ÙŠØ¶, ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø§Ù„ØªØ´Ø®ÙŠØµ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ PCR, Ø£Ø¬Ù‡Ø²Ø© POCT, Ø£Ø¬Ù‡Ø²Ø© ICU",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ù…ÙˆÙ„Ø¯Ø§Øª Ø®Ø§ØµØ© Ù…Ø¹ Ø£Ù†Ø¸Ù…Ø© Ø­Ù…Ø§ÙŠØ© ÙˆÙ…Ø«Ø¨ØªØ§Øª Ø¬Ù‡Ø¯",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù…Ù† 5,000 Ø¥Ù„Ù‰ 15,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-029",
    "name": "Ø¯. / Ù…. Abdalaliem faiz",
    "rawName": "Abdalaliem faiz",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249923 *** 4918",
    "emailMasked": "b***y@gmail.com",
    "field": "Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠÙ‡",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… ØªÙ‚Ù†ÙŠ / ÙÙ†ÙŠ",
    "univ": "Ù…Ø§Ø±Ø³ØªÙ‡Ø§ Ù…ÙŠØ¯Ø§Ù†ÙŠØ§Ù‹",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø£Ø´Ø¹Ø© Ø§Ù„ØªØ´Ø®ÙŠØµÙŠØ© ÙˆØ§Ù„Ù…ÙˆØ¬Ø§Øª Ø§Ù„ØµÙˆØªÙŠØ©",
    "cbcFocus": "Ù„Ø§ Ø£Ø¹Ù…Ù„ ÙÙŠ Ø®Ø·ÙˆØ· ØµÙˆØ±Ø© Ø§Ù„Ø¯Ù… Ø­Ø§Ù„ÙŠØ§Ù‹",
    "powerStrategy": "Ø£Ù†Ø¸Ù…Ø© Ø§Ù„ØªØ®Ø²ÙŠÙ† Ø§Ù„Ù…Ø¤Ù‚Øª UPS",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-030",
    "name": "Ø¯. / Ù…. Ø­Ø§Ø²Ù… Ø¹Ù…Ø± Ø¨Ø­Ø±",
    "rawName": "Ø­Ø§Ø²Ù… Ø¹Ù…Ø± Ø¨Ø­Ø±",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249992 *** 7404",
    "emailMasked": "h***1@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ù…Ø³ØªÙ‚Ø¨Ù„",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¨Ø­Ø± Ø§Ù„Ø£Ø­Ù…Ø± (Ø¨ÙˆØ±ØªØ³ÙˆØ¯Ø§Ù† / Ø³ÙˆØ§ÙƒÙ†)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø£Ø¬Ù‡Ø²Ø© POCT, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø£Ø´Ø¹Ø© ÙˆØ§Ù„Ø£Ø³Ù†Ø§Ù†",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Sysmex XN, Mindray BC-6000)",
    "powerStrategy": "ØªØ¶Ø±Ø± Ø§Ù„Ù„ÙˆØ­Ø§Øª Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ù„Ø£Ø¬Ù‡Ø²Ø©",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD004-SCI-MTC1-BRZ",
    "name": "Ø¯. / Ù…. Ù…Ø¤ÙŠØ¯ Ø§Ø­Ù…Ø¯ Ø­Ø§Ù…Ø¯ Ù‚Ù…Ø± Ø§Ù„Ø¯ÙŠÙ†",
    "rawName": "Ù…Ø¤ÙŠØ¯ Ø§Ø­Ù…Ø¯ Ø­Ø§Ù…Ø¯ Ù‚Ù…Ø± Ø§Ù„Ø¯ÙŠÙ†",
    "entity": "Ù†Ø¨Ø¶ Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249905 *** 8004",
    "emailMasked": "m***0@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù… Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø¥Ø³Ù„Ø§Ù…ÙŠØ©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Sysmex XN, Mindray)",
    "powerStrategy": "ØªØ¶Ø±Ø± Ø§Ù„Ù„ÙˆØ­Ø§Øª Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ù„Ø£Ø¬Ù‡Ø²Ø©",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù…Ù† 2,000 Ø¥Ù„Ù‰ 5,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD594-SCI-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Moram hashim khider abdalla",
    "rawName": "Moram hashim khider abdalla",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249119 *** 8594",
    "emailMasked": "m***0@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… Ø¹Ø§Ù„ÙŠ / ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "ÙƒÙ„ÙŠØ© Ø§Ù„ÙŠØ±Ù…ÙˆÙƒ",
    "regions": "Ø§Ù„ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø´Ù…Ø§Ù„ÙŠØ© (Ø¯Ù†Ù‚Ù„Ø§ / Ù…Ø±ÙˆÙŠ / ÙˆØ§Ø¯ÙŠ Ø­Ù„ÙØ§), ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„, ØºØ§Ø²Ø§Øª Ø§Ù„Ø¯Ù…",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ù…ÙˆÙ„Ø¯Ø§Øª Ø®Ø§ØµØ© Ù…Ø¹ Ø£Ù†Ø¸Ù…Ø© Ø­Ù…Ø§ÙŠØ© ÙˆÙ…Ø«Ø¨ØªØ§Øª Ø¬Ù‡Ø¯",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD125-DNT-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Mohammed Abd ALmohsin Mohammed babkir",
    "rawName": "Mohammed Abd ALmohsin Mohammed babkir",
    "entity": "Dar med heath & education",
    "phoneMasked": "249968 *** 5861",
    "emailMasked": "m***9@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø·Ø¨ ÙˆØ¬Ø±Ø§Ø­Ø© Ø§Ù„Ø£Ø³Ù†Ø§Ù† ÙˆÙ…Ø³ØªÙ„Ø²Ù…Ø§ØªÙ‡Ø§",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø±Ø§Ø²ÙŠ _ ÙƒÙ„ÙŠØ© Ø·Ø¨ ÙˆØ¬Ø±Ø§Ø­Ø© Ø§Ù„ÙÙ… Ùˆ Ø§Ù„Ø£Ø³Ù†Ø§Ù†",
    "regions": "Ø§Ù„ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø´Ù…Ø§Ù„ÙŠØ© (Ø¯Ù†Ù‚Ù„Ø§ / Ù…Ø±ÙˆÙŠ), ÙˆÙ„Ø§ÙŠØ© Ù†Ù‡Ø± Ø§Ù„Ù†ÙŠÙ„ (Ø´Ù†Ø¯ÙŠ / Ø¹Ø·Ø¨Ø±Ø©), ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ…",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, Ø£Ø¬Ù‡Ø²Ø© POCT, Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø£Ø´Ø¹Ø©, Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø£Ø³Ù†Ø§Ù†",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø£Ù†Ø¸Ù…Ø© Ø§Ù„ØªØ®Ø²ÙŠÙ† Ø§Ù„Ù…Ø¤Ù‚Øª UPS Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ØµØºÙŠØ±Ø©",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD665-SCI-MTC1-BRZ",
    "name": "Ø¯. / Ù…. Ù…Ø¤ÙŠØ¯ Ø­ÙŠØ¯Ø± Ø¨Ø·Ø±Ø§Ù† Ø¥Ø¯Ø±ÙŠØ³",
    "rawName": "Ù…Ø¤ÙŠØ¯ Ø­ÙŠØ¯Ø± Ø¨Ø·Ø±Ø§Ù† Ø¥Ø¯Ø±ÙŠØ³",
    "entity": "Ø´Ø±ÙƒØ© Ø§Ù„Ø´Ù‡Ø¨Ø§Ø¡ Ù„Ù„Ø£Ø¯ÙˆÙŠØ© Ùˆ Ø§Ù„Ù…Ø¹Ø¯Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249997 *** 2924",
    "emailMasked": "M***9@gmail.com",
    "field": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¨Ø´Ø±ÙŠ ÙˆØ§Ù„Ø¬Ø±Ø§Ø­Ø©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¥Ù…Ø§Ù… Ø§Ù„Ù…Ù‡Ø¯ÙŠ _ ÙƒÙ„ÙŠØ© Ø§Ù„Ø·Ø¨ ÙˆØ§Ù„Ø¬Ø±Ø§Ø­Ø©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ù†ÙŠÙ„ Ø§Ù„Ø£Ø¨ÙŠØ¶ (ÙƒÙˆØ´ØªÙŠ / Ø±Ø¨Ùƒ / Ø§Ù„Ù‚Ø·ÙŠÙ†Ø© / Ø§Ù„Ø¯ÙˆÙŠÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD288-MLS-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Ø¹Ø¨Ø¯Ø§Ù„Ø­Ù„ÙŠÙ… Ù…ÙƒÙŠ Ø­Ø³Ù† Ù…Ø­Ù…Ø¯ Ø¹Ù„ÙŠ",
    "rawName": "Ø¹Ø¨Ø¯Ø§Ù„Ø­Ù„ÙŠÙ… Ù…ÙƒÙŠ Ø­Ø³Ù† Ù…Ø­Ù…Ø¯ Ø¹Ù„ÙŠ",
    "entity": "Ù…Ø³ØªÙˆØµÙ Ø§Ù„Ø´ÙØ§Ø¡ Ø§Ù„Ø·Ø¨ÙŠ",
    "phoneMasked": "249917 *** 8288",
    "emailMasked": "A***i@Jmil.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… ØªÙ‚Ù†ÙŠ / ÙÙ†ÙŠ",
    "univ": "ÙƒÙ„ÙŠÙ‡ Ø§Ù„Ø·Ø¨ ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„ØµØ­ÙŠÙ‡ Ø¬Ø§Ù…Ø¹Ù‡ ÙƒØ³Ù„Ø§",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ù‚Ø¶Ø§Ø±Ù, ÙˆÙ„Ø§ÙŠØ© ÙƒØ³Ù„Ø§",
    "equipmentFocus": "Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª Ø§Ù„Ù…Ø¹Ø§Ù…Ù„ Ø§Ù„Ø¹Ø§Ù…Ø© ÙˆØ³Ø­Ø¨ Ø§Ù„Ø¯Ù…",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ù…ÙˆÙ„Ø¯Ø§Øª Ø®Ø§ØµØ© Ù…Ø¹ Ø£Ù†Ø¸Ù…Ø© Ø­Ù…Ø§ÙŠØ© ÙˆÙ…Ø«Ø¨ØªØ§Øª Ø¬Ù‡Ø¯",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD240-ENG-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Ø§Ø­Ù…Ø¯ Ø­Ø³Ù† ÙŠÙˆØ³Ù Ø¹Ù…Ø±",
    "rawName": "Ø§Ø­Ù…Ø¯ Ø­Ø³Ù† ÙŠÙˆØ³Ù Ø¹Ù…Ø±",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249907 *** 2240",
    "emailMasked": "a***9@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø²Ø¹ÙŠÙ… Ø§Ù„Ø§Ø²Ù‡Ø±ÙŠ",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-SD533-MLS-AFM1-BRZ",
    "name": "Ø¯. / Ù…. Hussein Mohammed Hamid Mohammed",
    "rawName": "Hussein Mohammed Hamid Mohammed",
    "entity": "Ù†Ù…Ø± Ø§Ù„ÙØ±ÙˆØ¹ Ù„Ù„Ù…Ø³ØªÙ‡Ù„ÙƒØ§Øª ÙˆØ§Ù„Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249961 *** 6533",
    "emailMasked": "l***n@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… Ø¹Ø§Ù„ÙŠ / ÙÙˆÙ‚ Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙ‚Ø§Ù†Ø©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©, ØºØ§Ø²Ø§Øª Ø§Ù„Ø¯Ù…, Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø§Ù„Ø£Ø³Ù†Ø§Ù†",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part Ùˆ 5-part (Sysmex XN, Mindray)",
    "powerStrategy": "Ø£Ù†Ø¸Ù…Ø© Ø§Ù„ØªØ®Ø²ÙŠÙ† Ø§Ù„Ù…Ø¤Ù‚Øª UPS Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ØµØºÙŠØ±Ø©",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ù…Ù† 2,000 Ø¥Ù„Ù‰ 5,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-038",
    "name": "Ø¯. / Ù…. ÙˆØ§Ø¦Ù„ ÙØªØ­ Ø§Ù„Ø±Ø­Ù…Ù†",
    "rawName": "ÙˆØ§Ø¦Ù„ ÙØªØ­ Ø§Ù„Ø±Ø­Ù…Ù†",
    "entity": "ÙˆØ±Ø´Ø© ØµØ§Ø¨Ø±ÙŠÙ† Ù„Ù„Ø§Ø«Ø§Ø«Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "phoneMasked": "249100 *** 5380",
    "emailMasked": "w***9@gmail.com",
    "field": "Ø£Ø®Ø±Ù‰",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø§Ù„ÙƒÙ„ÙŠØ© Ø§Ù„Ø§Ø±Ø¯Ù†ÙŠØ© Ø§Ù„Ø³ÙˆØ¯Ø§Ù†ÙŠØ© Ù„Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø®Ø±Ø·ÙˆÙ… (Ø£Ù… Ø¯Ø±Ù…Ø§Ù† / Ø¨Ø­Ø±ÙŠ / Ø§Ù„Ø®Ø±Ø·ÙˆÙ…)",
    "equipmentFocus": "Ù…Ø³ØªÙ„Ø²Ù…Ø§Øª Ø·Ø¨ Ø§Ù„Ø£Ø³Ù†Ø§Ù† ÙˆØ§Ù„Ø£Ø«Ø§Ø«Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ù…ÙˆÙ„Ø¯Ø§Øª Ø®Ø§ØµØ© Ù…Ø¹ Ø£Ù†Ø¸Ù…Ø© Ø­Ù…Ø§ÙŠØ© ÙˆÙ…Ø«Ø¨ØªØ§Øª Ø¬Ù‡Ø¯",
    "bufferStock": "ØªÙˆØ±ÙŠØ¯ ÙÙˆØ±ÙŠ Ø£Ø³Ø¨ÙˆØ¹ÙŠ Just-in-Time",
    "monthlyCapacity": "Ø£Ù‚Ù„ Ù…Ù† 2,000 Ø¯ÙˆÙ„Ø§Ø± Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-039",
    "name": "Ø¯. / Ù…. Ø£Ø´Ø±Ù Ø¹Ù…Ø§Ø¯ Ø§Ù„Ø¯ÙŠÙ† Ù‡Ø§Ø´Ù… Ù…ÙˆØ³ÙŠ",
    "rawName": "Ø£Ø´Ø±Ù Ø¹Ù…Ø§Ø¯ Ø§Ù„Ø¯ÙŠÙ† Ù‡Ø§Ø´Ù… Ù…ÙˆØ³ÙŠ",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "249911 *** 9697",
    "emailMasked": "a***n@gmail.com",
    "field": "Ù‡Ù†Ø¯Ø³Ø© Ø·Ø¨ÙŠØ© Ø­ÙŠÙˆÙŠØ© / ØµÙŠØ§Ù†Ø© Ù…Ø¹Ø¯Ø§Øª Ø·Ø¨ÙŠØ©",
    "education": "Ø¯Ø¨Ù„ÙˆÙ… ØªÙ‚Ù†ÙŠ / ÙÙ†ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¬Ø²ÙŠØ±Ø©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© (ÙˆØ¯ Ù…Ø¯Ù†ÙŠ / Ø§Ù„Ù…Ù†Ø§Ù‚Ù„)",
    "equipmentFocus": "Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ø±Ø¹Ø§ÙŠØ© Ø§Ù„Ø­Ø±Ø¬Ø© ÙˆØ§Ù„Ø¹Ù†Ø§ÙŠØ© Ø§Ù„Ù…ÙƒØ«ÙØ© ÙˆØ§Ù„ØªØ®Ø¯ÙŠØ± (ICU)",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 5-part (Horiba Yumizen, Sysmex, Mindray)",
    "powerStrategy": "Ø£Ù†Ø¸Ù…Ø© Ø§Ù„ØªØ®Ø²ÙŠÙ† Ø§Ù„Ù…Ø¤Ù‚Øª UPS Ù„Ù„Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ØµØºÙŠØ±Ø©",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† ÙŠÙƒÙÙŠ Ù„ØªØºØ·ÙŠØ© Ø´Ù‡Ø± ÙˆØ§Ø­Ø¯ ØªØ´ØºÙŠÙ„ÙŠ",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": true,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  },
  {
    "id": "GLOMEt-PT-040",
    "name": "Ø¯. / Ù…. Dfaalla altom dfaalla",
    "rawName": "Dfaalla altom dfaalla",
    "entity": "ÙˆÙƒÙŠÙ„ / Ù…Ù†Ø¯ÙˆØ¨ Ù…Ø³ØªÙ‚Ù„",
    "phoneMasked": "002499 *** 3935",
    "emailMasked": "D***6@gmail.com",
    "field": "Ø¹Ù„ÙˆÙ… Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ©",
    "education": "Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠÙˆØ³ / Ø¬Ø§Ù…Ø¹ÙŠ",
    "univ": "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù…Ø¯Ø±Ù…Ø§Ù† Ø§Ù„Ø§Ø³Ù„Ø§Ù…ÙŠØ©",
    "regions": "ÙˆÙ„Ø§ÙŠØ© Ø§Ù„Ù†ÙŠÙ„ Ø§Ù„Ø£Ø²Ø±Ù‚ (Ø§Ù„Ø¯Ù…Ø§Ø²ÙŠÙ†)",
    "equipmentFocus": "Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¯Ù…, Ø§Ù„ÙƒÙŠÙ…ÙŠØ§Ø¡ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©, Ø§Ù„Ø£Ø­ÙŠØ§Ø¡ Ø§Ù„Ø¯Ù‚ÙŠÙ‚Ø©",
    "cbcFocus": "Ø£Ù†Ø¸Ù…Ø© CBC 3-part",
    "powerStrategy": "Ø·Ø§Ù‚Ø© Ø´Ù…Ø³ÙŠØ© ÙˆØ¨Ø·Ø§Ø±ÙŠØ§Øª",
    "bufferStock": "Ù…Ø®Ø²ÙˆÙ† Ø§Ø³ØªØ±Ø§ØªÙŠØ¬ÙŠ Ù…Ù† Ø´Ù‡Ø±ÙŠÙ† Ø¥Ù„Ù‰ 3 Ø£Ø´Ù‡Ø±",
    "monthlyCapacity": "Ù„Ø§ Ø§Ø³ØªØ·ÙŠØ¹ Ø§Ù„ØªÙ‚Ø¯ÙŠØ±",
    "biomedicalUnit": false,
    "tier": "B2B Partner",
    "status": "Accredited Distributor"
  }
];

const GLOMET_PARTNERS_METRICS = {
  totalPartners: 40,
  statesCovered: 10,
  biomedicalEngineeringCount: 11,
  corporateEntitiesCount: 6,
  independentBrokersCount: 22
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GLOMET_PARTNERS_DATABASE, GLOMET_PARTNERS_METRICS };
}
