const PROGRAMS_DATABASE = [
  {
    "code": "SMC-101",
    "title": "Internal Medicine & Systemic Pathophysiology (MTCâ„¢ 1.0)",
    "title_ar": "Ø§Ù„Ø¨Ø§Ø·Ù†ÙŠØ© Ø§Ù„Ø¹Ø§Ù…Ø© ÙˆØ§Ù„ÙÙŠØ²ÙŠÙˆÙ„ÙˆØ¬ÙŠØ§ Ø§Ù„Ù…Ø±Ø¶ÙŠØ© Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 1,
    "ects": 4.0,
    "sch": 3.0,
    "hours": 120,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Clinical Nephrology & Cardiology Fellows",
      "accountable": "Dr. Mohamed Gibbril (Academic Director)",
      "consulted": "Internal Medicine Board & Dr. Alaa Mursi",
      "informed": "Enrolled Candidate (GA-ID), SudaPass Ledger"
    },
    "description": "Quantitative management of fluid/electrolyte disturbances (AdroguÃ©-Madias sodium deficit calculation), acute coronary syndromes, DKA titration, and acid-base blood gas interpretation."
  },
  {
    "code": "SMC-102",
    "title": "General Surgery & Acute Surgical Emergencies (MTCâ„¢ 2.0)",
    "title_ar": "Ø§Ù„Ø¬Ø±Ø§Ø­Ø© Ø§Ù„Ø¹Ø§Ù…Ø© ÙˆØ·ÙˆØ§Ø±Ø¦ Ø§Ù„Ø¥ØµØ§Ø¨Ø§Øª Ø§Ù„Ø¬Ø±Ø§Ø­ÙŠØ©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 2,
    "ects": 4.0,
    "sch": 3.0,
    "hours": 120,
    "instructor": "Surgical Faculty Board",
    "raci": {
      "responsible": "Surgical Emergency Senior Registrar",
      "accountable": "Surgical Faculty Board & Dr. Mohamed Gibbril",
      "consulted": "Consultant Trauma Surgeons (Partner Hospitals)",
      "informed": "Enrolled Candidate, SudaPass Ledger"
    },
    "description": "Acute abdomen triage, tension pneumothorax needle decompression, hemorrhagic shock resuscitation, acute limb ischemia, and surgical site infection management."
  },
  {
    "code": "SMC-103",
    "title": "Obstetrics & Gynecology (MTCâ„¢ 3.0)",
    "title_ar": "Ø§Ù„Ù†Ø³Ø§Ø¡ ÙˆØ§Ù„ØªÙˆÙ„ÙŠØ¯ ÙˆØ­Ø§Ù„Ø§Øª Ø§Ù„Ø·ÙˆØ§Ø±Ø¦ Ø§Ù„Ø­Ø±Ø¬Ø©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 3,
    "ects": 3.5,
    "sch": 2.5,
    "hours": 105,
    "instructor": "Obs/Gyn Senior Faculty",
    "raci": {
      "responsible": "Obs/Gyn Clinical Demonstrator",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Maternal-Fetal Medicine Board",
      "informed": "Enrolled Candidate, SudaPass Ledger"
    },
    "description": "Postpartum hemorrhage (PPH) medical/surgical protocols, pre-eclampsia magnesium sulfate regimens, fetal distress CTG interpretation, and ectopic pregnancy protocols."
  },
  {
    "code": "SMC-104",
    "title": "Pediatrics & Neonatal Resuscitation (MTCâ„¢ 4.0)",
    "title_ar": "Ø·Ø¨ Ø§Ù„Ø£Ø·ÙØ§Ù„ ÙˆØ§Ù„Ø¥Ù†Ø¹Ø§Ø´ Ø§Ù„ÙˆÙ„ÙŠØ¯ÙŠ Ø§Ù„Ù…ØªÙ‚Ø¯Ù…",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 4,
    "ects": 3.5,
    "sch": 2.5,
    "hours": 105,
    "instructor": "Pediatric Emergency Faculty",
    "raci": {
      "responsible": "Pediatric Emergency Registrar",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Pediatric Board & NICU Specialists",
      "informed": "Enrolled Candidate, SudaPass Ledger"
    },
    "description": "Neonatal resuscitation (NRP) algorithms, severe pediatric dehydration fluid calculations, foreign body airway obstruction, status epilepticus, and severe malaria protocol."
  },
  {
    "code": "SMC-105",
    "title": "Medical Ethics, Forensic Medicine & SudaPass Standards (MTCâ„¢ 5.0)",
    "title_ar": "Ø§Ù„Ø£Ø®Ù„Ø§Ù‚ÙŠØ§Øª Ø§Ù„Ø·Ø¨ÙŠØ© ÙˆØ§Ù„Ø·Ø¨ Ø§Ù„Ø´Ø±Ø¹ÙŠ ÙˆÙ…Ø¹Ø§ÙŠÙŠØ± SudaPass",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 5,
    "ects": 2.0,
    "sch": 1.5,
    "hours": 60,
    "instructor": "Governance Board",
    "raci": {
      "responsible": "Forensic Medicine & Ethics Fellow",
      "accountable": "Governance Board & Dr. Mohamed Gibbril",
      "consulted": "Legal Counsel & Medical Council Committee",
      "informed": "Candidate, SudaPass Ledger, Partner Hospitals"
    },
    "description": "Clinical negligence, informed consent in emergencies, death certification, forensic traumatology, professional doctor-patient boundary standards, and SudaPass verification protocols."
  },
  {
    "code": "SMC-106",
    "title": "Clinical Pharmacology & Toxicology (MTCâ„¢ 6.0)",
    "title_ar": "Ø¹Ù„Ù… Ø§Ù„Ø£Ø¯ÙˆÙŠØ© Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ© ÙˆØ§Ù„Ø³Ù…ÙˆÙ… Ø§Ù„Ø·Ø§Ø±Ø¦Ø©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 6,
    "ects": 3.0,
    "sch": 2.0,
    "hours": 90,
    "instructor": "Dr. Alaa Mursi",
    "raci": {
      "responsible": "Clinical Pharmacologist Fellow",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Dr. Alaa Mursi",
      "informed": "Enrolled Candidate, SudaPass Ledger"
    },
    "description": "Antimicrobial stewardship, therapeutic drug monitoring (vancomycin/aminoglycosides), autonomic toxidromes (organophosphates, paracetamol overdose, opioids), and cardiac drug titration."
  },
  {
    "code": "SMC-107",
    "title": "Diagnostic Radiology & Laboratory Medicine (MTCâ„¢ 7.0)",
    "title_ar": "Ø§Ù„Ø£Ø´Ø¹Ø© Ø§Ù„ØªØ´Ø®ÙŠØµÙŠØ© ÙˆÙ‚Ø±Ø§Ø¡Ø© Ø§Ù„ØªØ­Ø§Ù„ÙŠÙ„ Ø§Ù„Ù…Ø®Ø¨Ø±ÙŠØ©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 7,
    "ects": 2.5,
    "sch": 2.0,
    "hours": 75,
    "instructor": "Diagnostic Faculty Board",
    "raci": {
      "responsible": "Radiology Clinical Demonstrator",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Diagnostic Imaging Board & GLOMEt Specialists",
      "informed": "Enrolled Candidate, SudaPass Ledger"
    },
    "description": "Systematic chest X-ray interpretation, emergency brain CT (ischemic stroke vs intracranial hemorrhage), FAST ultrasound in trauma, and CBC/LFT/RFT pattern analysis."
  },
  {
    "code": "SMC-108",
    "title": "Community Medicine, Public Health & Epidemiology (MTCâ„¢ 8.0)",
    "title_ar": "Ø·Ø¨ Ø§Ù„Ù…Ø¬ØªÙ…Ø¹ ÙˆØ§Ù„ØµØ­Ø© Ø§Ù„Ø¹Ø§Ù…Ø© ÙˆØ§Ù„ÙˆØ¨Ø§Ø¦ÙŠØ§Øª Ø§Ù„Ø¥Ù‚Ù„ÙŠÙ…ÙŠØ©",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Clinical Licensure (SMC 1-8)",
    "level": 5,
    "sort_order": 8,
    "ects": 2.5,
    "sch": 2.0,
    "hours": 75,
    "instructor": "Epidemiology Board",
    "raci": {
      "responsible": "Public Health Epidemiologist",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Regional Epidemiology Unit (GLOMEt)",
      "informed": "Candidate, Ministry Health Observers, SudaPass Ledger"
    },
    "description": "Outbreak investigation, vaccine schedules, maternal and child health indicators, biostatistics (odds ratios, relative risk, sensitivity/specificity), and regional disease surveillance."
  },
  {
    "code": "SURG-201",
    "title": "MRCS Part A Foundation Sciences & Critical Care",
    "title_ar": "Ø§Ù„Ø²Ù…Ø§Ù„Ø© Ø§Ù„Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ© Ù„Ù„Ø¬Ø±Ø§Ø­Ø© MRCS Ø§Ù„Ø¬Ø²Ø¡ Ø§Ù„Ø£ÙˆÙ„",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "International Fellowships",
    "level": 5,
    "sort_order": 9,
    "ects": 5.0,
    "sch": 3.5,
    "hours": 150,
    "instructor": "Surgical Training Board",
    "raci": {
      "responsible": "Surgical Training Fellow",
      "accountable": "Surgical Faculty Board & Dr. Mohamed Gibbril",
      "consulted": "UK/Irish Royal Colleges Alumni Group",
      "informed": "Candidate, Surgical Portfolio Registrar"
    },
    "description": "Intercollegiate MRCS Part A syllabus: regional surgical anatomy, systemic pathology, surgical microbiology, trauma resuscitation, and perioperative care."
  },
  {
    "code": "GERM-206",
    "title": "The GermanGemIInI Approbation & FSP Language Track",
    "title_ar": "Ø§Ù„Ù…Ø¹Ø§Ø¯Ù„Ø© Ø§Ù„Ø·Ø¨ÙŠØ© Ø§Ù„Ø£Ù„Ù…Ø§Ù†ÙŠØ© ÙˆØ§Ø®ØªØ¨Ø§Ø± Ø§Ù„Ù„ØºØ© Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ© FSP",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "International Fellowships",
    "level": 5,
    "sort_order": 10,
    "ects": 5.0,
    "sch": 3.5,
    "hours": 150,
    "instructor": "German Medical Faculty",
    "raci": {
      "responsible": "German Pathway Fellow (Approbation holder)",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "German Healthcare Integration Council",
      "informed": "Candidate, GermanGemIInI Workspace"
    },
    "description": "Complete pathway for medical licensing in Germany: FachsprachenprÃ¼fung (FSP) clinical communication simulation, Arzt-Patienten-GesprÃ¤ch, Arztbrief documentation, and KenntnisprÃ¼fung (KP) clinical foundation."
  },
  {
    "code": "SKILL-301",
    "title": "Basic Surgical Skills Cohort (BSS-1 & BSS-2 Hands-On)",
    "title_ar": "Ø¯ÙØ¹Ø§Øª Ø§Ù„Ù…Ù‡Ø§Ø±Ø§Øª Ø§Ù„Ø¬Ø±Ø§Ø­ÙŠØ© Ø§Ù„Ø£Ø³Ø§Ø³ÙŠØ© BSS-1 & BSS-2",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Surgical & Simulation Skills",
    "level": 4,
    "sort_order": 11,
    "ects": 3.0,
    "sch": 2.0,
    "hours": 90,
    "instructor": "Cairo Hub Surgical Faculty",
    "raci": {
      "responsible": "Surgical Simulation Demonstrator",
      "accountable": "Surgical Faculty Board & Dr. Mohamed Gibbril",
      "consulted": "Cairo Simulation Center Lead",
      "informed": "Candidate, Verified Surgical Logbook, SudaPass Ledger"
    },
    "description": "Hands-on psychomotor simulation: instrument handling, suturing geometry, deep cavity tying, bowel anastomosis, vascular repair techniques, and laparoscopic box trainer navigation."
  },
  {
    "code": "SKILL-303",
    "title": "Basic Life Support & Critical Resuscitation (BLS 105-Hour Track)",
    "title_ar": "Ø§Ù„Ø¥Ù†Ø¹Ø§Ø´ Ø§Ù„Ù‚Ù„Ø¨ÙŠ Ø§Ù„Ø±Ø¦ÙˆÙŠ Ø§Ù„Ø£Ø³Ø§Ø³ÙŠ Ø§Ù„Ù…Ø¹ØªÙ…Ø¯ (105 Ø³Ø§Ø¹Ø§Øª)",
    "pillar": "GemIInI Academy",
    "pillar_color": "teal",
    "category": "Surgical & Simulation Skills",
    "level": 4,
    "sort_order": 12,
    "ects": 3.5,
    "sch": 2.5,
    "hours": 105,
    "instructor": "Resuscitation Faculty",
    "raci": {
      "responsible": "Certified Resuscitation Instructor",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Emergency & Critical Care Board",
      "informed": "Candidate, SudaPass CPD Ledger (40 CME/CPD Credit Verified)"
    },
    "description": "High-intensity clinical resuscitation: adult/pediatric/infant CPR, Bag-Valve-Mask ventilation, AED defibrillation, choking relief, and team dynamics during cardiac arrest."
  },
  {
    "code": "MM-101",
    "title": "Molecular Medicine MM 1.0 â€” DNA Architecture & Topology",
    "title_ar": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ 1.0: Ø¨Ù†ÙŠØ© Ø§Ù„Ù€ DNA ÙˆØ¯ÙŠÙ†Ø§Ù…ÙŠÙƒÙŠØ© Ø§Ù„Ø§Ù„ØªÙØ§Ù Ø§Ù„ÙØ§Ø¦Ù‚",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Molecular Medicine (MM 1.0-8.0)",
    "level": 4,
    "sort_order": 13,
    "ects": 2.5,
    "sch": 2.0,
    "hours": 75,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Molecular Biology Fellow",
      "accountable": "Dr. Mohamed Gibbril (Founder & Director)",
      "consulted": "Dr. Alaa Mursi",
      "informed": "Enrolled Fellow, GeneAcademy Research Registry"
    },
    "description": "DNA secondary/tertiary structure, B/A/Z-DNA conformations, chromatin packaging, histone acetyltransferases/deacetylases, topoisomerase I/II mechanics, and DNA replication fidelity."
  },
  {
    "code": "MM-102",
    "title": "Molecular Medicine MM 2.0 â€” RNA Biology & Transcriptomics",
    "title_ar": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ 2.0: Ø¨ÙŠÙˆÙ„ÙˆØ¬ÙŠØ§ Ø§Ù„Ù€ RNA ÙˆØ§Ù„Ù†Ø³Ø® Ø§Ù„Ø¬ÙŠÙ†ÙŠ",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Molecular Medicine (MM 1.0-8.0)",
    "level": 4,
    "sort_order": 14,
    "ects": 2.5,
    "sch": 2.0,
    "hours": 75,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Transcriptomics Research Fellow",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Dr. Alaa Mursi",
      "informed": "Fellow, SudaPass Central Ledger"
    },
    "description": "RNA polymerases, promoter architecture, spliceosome assembly, alternative splicing in pathology, long non-coding RNAs (lncRNAs), microRNAs, and quantitative RNA-seq analytics."
  },
  {
    "code": "MM-104",
    "title": "Molecular Medicine MM 4.0 â€” Viral & Cellular Oncogenesis",
    "title_ar": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ 4.0: Ø§Ù„ØªØ³Ø±Ø·Ù† Ø§Ù„ÙÙŠØ±ÙˆØ³ÙŠ ÙˆØ§Ù„Ø®Ù„ÙˆÙŠ ÙˆÙ†Ù‚Ø§Ø· p53/Rb",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Molecular Medicine (MM 1.0-8.0)",
    "level": 4,
    "sort_order": 15,
    "ects": 3.0,
    "sch": 2.0,
    "hours": 90,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Oncology Research Fellow",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Molecular Pathology Consultant Board",
      "informed": "Candidate, Research Pod #1 Lead"
    },
    "description": "Hallmarks of cancer, proto-oncogene activation (RAS, MYC), tumor suppressor loss (TP53, RB1), viral oncogenesis (HPV E6/E7, EBV LMP1, HBV/HCV), and targeted immunotherapy."
  },
  {
    "code": "MM-105",
    "title": "Molecular Medicine MM 5.0 â€” Recombinant DNA & CRISPR-Cas9",
    "title_ar": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ 5.0: ØªÙ‚Ù†ÙŠØ§Øª Ø§Ù„Ù€ DNA Ø§Ù„Ù…Ø¹Ø§Ø¯ ØªØ±ÙƒÙŠØ¨Ù‡ ÙˆØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø¬ÙŠÙ†Ø§Øª",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Molecular Medicine (MM 1.0-8.0)",
    "level": 4,
    "sort_order": 16,
    "ects": 3.0,
    "sch": 2.0,
    "hours": 90,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Genetic Engineering Fellow",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Dr. Alaa Mursi",
      "informed": "Candidate, SudaPass Central Ledger"
    },
    "description": "Restriction endonucleases, plasmid cloning, cDNA synthesis, PCR primer design, recombinant expression systems, and CRISPR-Cas9 gene editing mechanics and off-target analysis."
  },
  {
    "code": "MM-108",
    "title": "Molecular Medicine MM 8.0 â€” Clinical Whole Exome Sequencing (WES)",
    "title_ar": "Ø§Ù„Ø·Ø¨ Ø§Ù„Ø¬Ø²ÙŠØ¦ÙŠ 8.0: ØªÙØ³ÙŠØ± Ø§Ù„ÙØ­Øµ Ø§Ù„Ø¬ÙŠÙ†ÙŠ Ø§Ù„ÙƒØ§Ù…Ù„ WES ÙˆÙ…Ø¹Ø§ÙŠÙŠØ± ACMG",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Molecular Medicine (MM 1.0-8.0)",
    "level": 4,
    "sort_order": 17,
    "ects": 3.5,
    "sch": 2.5,
    "hours": 105,
    "instructor": "Dr. Mohamed Gibbril",
    "raci": {
      "responsible": "Lead Bioinformatician & Clinical Geneticist",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Clinical Genomics Diagnostic Board & Dr. Alaa Mursi",
      "informed": "Fellow, Clinical Genetics Registry, SudaPass Ledger"
    },
    "description": "Next-Generation Sequencing (NGS) pipeline: FASTQ quality control, BAM alignment, VCF variant calling, population frequency filtering (gnomAD), in silico pathogenicity algorithms (SIFT, PolyPhen, CADD), and ACMG 5-tier classification reporting."
  },
  {
    "code": "POD-401",
    "title": "15:5:1 Research Pods â€” Translational Oncology & Liquid Biopsies",
    "title_ar": "Ù…Ø¬Ù…ÙˆØ¹Ø§Øª Ø§Ù„Ø£Ø¨Ø­Ø§Ø« 15:5:1 â€” Ø£ÙˆØ±Ø§Ù… Ø§Ù„Ø³Ø±Ø·Ø§Ù† ÙˆØ§Ù„Ø®Ø²Ø¹Ø§Øª Ø§Ù„Ø³Ø§Ø¦Ù„Ø©",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "15:5:1 Research Mentorship",
    "level": 4,
    "sort_order": 18,
    "ects": 4.0,
    "sch": 3.0,
    "hours": 120,
    "instructor": "Dr. Mohamed Gibbril (PI)",
    "raci": {
      "responsible": "Dr. Mohamed Gibbril (Principal Investigator)",
      "accountable": "Academic Governance Council",
      "consulted": "Oncology Faculty Board & Dr. Alaa Mursi",
      "informed": "5 University Researchers, 15 Pre-Meds, Publication Repository"
    },
    "description": "Active research pod investigating circulating tumor DNA (ctDNA) and cell-free RNA signatures in GI and breast carcinomas across Sudanese and regional cohorts."
  },
  {
    "code": "RESC-501",
    "title": "100 Papers Project & Academic Thesis Rescue Pipeline",
    "title_ar": "Ù…Ø´Ø±ÙˆØ¹ Ø§Ù„Ù€ 100 ÙˆØ±Ù‚Ø© Ø¨Ø­Ø«ÙŠØ© ÙˆØ§Ø³ØªÙƒÙ…Ø§Ù„ Ø§Ù„Ø£Ø·Ø±ÙˆØ­Ø§Øª Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠØ©",
    "pillar": "GeneAcademy",
    "pillar_color": "violet",
    "category": "Research & Academic Rescue",
    "level": 4,
    "sort_order": 19,
    "ects": 4.0,
    "sch": 3.0,
    "hours": 120,
    "instructor": "Thesis Mentor Board",
    "raci": {
      "responsible": "Thesis Mentor Panel",
      "accountable": "Dr. Mohamed Gibbril",
      "consulted": "Peer Review Advisory Board",
      "informed": "Displaced Candidate, University Affiliation Liaison"
    },
    "description": "Mentored completion of stalled Master's/PhD theses and clinical case reports for displaced doctors whose university programs were suspended."
  },
  {
    "code": "GLOM-601",
    "title": "Level 1-3 Turnkey Diagnostic Laboratory Engineering",
    "title_ar": "Ù‡Ù†Ø¯Ø³Ø© ÙˆØªØ¬Ù‡ÙŠØ² Ø§Ù„Ù…Ø®ØªØ¨Ø±Ø§Øª Ø§Ù„Ø·Ø¨ÙŠØ© Ø§Ù„Ù…ØªÙƒØ§Ù…Ù„Ø© (Ø§Ù„Ù…Ø³ØªÙˆÙŠØ§Øª 1-3)",
    "pillar": "GLOMEt HQ",
    "pillar_color": "gold",
    "category": "B2B Infrastructure & Supply",
    "level": 5,
    "sort_order": 20,
    "ects": 0.0,
    "sch": 0.0,
    "hours": 180,
    "instructor": "Biomedical Engineering Board",
    "raci": {
      "responsible": "Biomedical Installation & Cleanroom Engineers",
      "accountable": "GLOMEt Operations Director & Dr. Mohamed Gibbril",
      "consulted": "Hospital Medical Directors & Chief Lab Officers",
      "informed": "40 Verified Institutional Partners, GLOMEt Asset Registry"
    },
    "description": "Design, procurement, and installation of rapid emergency point-of-care diagnostics, automated 5-Part hematology/chemistry systems, and cleanroom molecular RT-PCR reference facilities."
  },
  {
    "code": "GLOM-701",
    "title": "Automated Hematology Reagent Forecasting & Cold-Chain Logistics",
    "title_ar": "Ù†Ù…Ø°Ø¬Ø© Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ ÙƒÙˆØ§Ø´Ù CBC ÙˆØ³Ù„Ø§Ø³Ù„ Ø§Ù„ØªÙˆØ±ÙŠØ¯ Ø§Ù„Ù…Ø¨Ø±Ø¯Ø©",
    "pillar": "GLOMEt HQ",
    "pillar_color": "gold",
    "category": "B2B Infrastructure & Supply",
    "level": 5,
    "sort_order": 21,
    "ects": 0.0,
    "sch": 0.0,
    "hours": 120,
    "instructor": "GLOMEt Logistics Board",
    "raci": {
      "responsible": "Reagent Logistics & Inventory Specialist",
      "accountable": "GLOMEt Operations Director",
      "consulted": "Hospital Laboratory Supervisors (40 Partners)",
      "informed": "Regional Distribution Warehouses (Port Sudan / Cairo)"
    },
    "description": "Predictive consumption algorithms for diluent, lyse, and cleaner packs based on monthly patient throughput, automated purge cycles, and solar-hybrid cold-chain preservation."
  }
];
