/**
 * GemIInI Sovereign Platform — Verified Operational Reviews & System Experience Database
 * Source: First Time Experience Form / استبيان تقييم تجربة نظام (2026)
 * Total Authenticated Doctor Submissions: 16
 * Privacy Notice: Personal Identifiable Information (PII) such as full email addresses
 * and direct phone numbers are cryptographically masked to protect candidate confidentiality.
 */

const GEMIINI_SURVEY_SCHEMA = {
  formTitle: "استبيان تقييم تجربة نظام GemIInI السيادي (First Time Experience & Operational Audit)",
  version: "2026.1",
  sections: [
    { id: "sec1", number: "1️⃣", title: "التحقق من الهوية الرقمية والربط المؤسسي", description: "Digital ID Verification & Institutional Linkage" },
    { id: "sec2", number: "2️⃣", title: "خارطة المجموعات والمسارات الحالية والمستقبلية", description: "Tracks & Question Bank Units" },
    { id: "sec3", number: "3️⃣", title: "تقييم وتجربة النظام والأسئلة (1 - 5 نجوم ⭐)", description: "Question Quality & System UX Ratings" },
    { id: "sec4", number: "4️⃣", title: "تفاعل السوشيال ميديا وجمع النقاط الفوري", description: "Social Media & Community Engagement" },
    { id: "sec5", number: "5️⃣", title: "تقييم بيئة المستخدم والتأثير الاستراتيجي", description: "Platform Clarity, Exclusivity & Adoption" },
    { id: "sec6", number: "6️⃣", title: "باقات الاستثمار الاستراتيجي وتفضيلات الدفع", description: "Pricing Willingness & Currency Selection" },
    { id: "sec7", number: "7️⃣", title: "مشاريع ومسارات التوسع المستقبلية", description: "Future GemIInI Expansion Tracks" },
    { id: "sec8", number: "8️⃣", title: "استمارة تقييم واقع الممارسة والتخصص الطبي بالسودان (SMSB Track)", description: "Sudan Medical Reality, SMSB Prep & Practice Barriers" },
    { id: "sec9", number: "9️⃣", title: "ضاعف نقاطك الآن (+100 نقطة إضافية) 🎁", description: "Colleague Nomination & Peer Referral" }
  ]
};

const GEMIINI_VERIFIED_REVIEWS = [
  {
    id: "REV-2026-001",
    timestamp: "2026-05-28 00:13:50",
    emailMasked: "m***i@gmail.com",
    gemiiniId: "GA3463",
    doctorName: "د. مودي حاتمي",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الثانية: طب المناطق الحارة والأمراض المستوطنة", "الوحدة الثالثة: الأمراض الباطنية والتخصصات السريرية المعتمدة"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)", "المسار الألماني (German Medical Pathway)", "مسار امتحان تنظيم الممارسة السوداني المحلي (SMC)"],
    nextTargetTrack: ["امتحان اللغة الطبية (OET)", "زمالة الكلية الملكية لطب الأطفال وصحة الطفل (MRCPCH)"],
    ratings: {
      questionQuality: 4,
      registrationEase1: 4,
      registrationEase2: 4,
      opsSupportSpeed: 5,
      communityInteraction: 4,
      overallAverage: 4.2
    },
    socialChannelsFollowed: ["صفحة فيسبوك المجتمعية الرسمية"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، ولكن كمصدر مساعد ومكمل بجانب الطرق التقليدية.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "5,000 SDG",
      pack800Q: "10,000 SDG",
      pack1200Q: "15,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["طب الأطفال وصحة الطفل", "أمراض النساء والتوليد"],
    sudanPracticeBarriers: ["عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم"],
    nominatedPeerPhoneMasked: "+249 92 *** 8807",
    keyHighlightQuote: "أول تجربة رائدة توازي الأنظمة العالمية في السوق. بنك أسئلة الجراحة والرعاية الحادة دقيق وسرعة الدعم ممتازة 5/5."
  },
  {
    id: "REV-2026-002",
    timestamp: "2026-05-28 01:40:57",
    emailMasked: "r***a@gmail.com",
    gemiiniId: "GA2980",
    doctorName: "د. رباح دفع الله",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الثانية: طب المناطق الحارة", "الوحدة الثالثة: الأمراض الباطنية", "الوحدة الرابعة: الجراحة الحادة", "الوحدة السابعة: طب الطوارئ والعناية المكثفة"],
    currentGroups: ["امتحان اللغة الطبية (OET)", "الطب الجزيئي (Molecular Medicine)", "دعم الحياة الأساسي (BLS)", "مسار امتحان تنظيم الممارسة السوداني (SMC)", "الأبحاث الطبية والكتابة العلمية"],
    nextTargetTrack: ["زمالة الكلية الملكية لطب الأطفال وصحة الطفل (MRCPCH)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 4,
      registrationEase2: 4,
      opsSupportSpeed: 5,
      communityInteraction: 4,
      overallAverage: 4.4
    },
    socialChannelsFollowed: ["صفحة فيسبوك المجتمعية الرسمية"],
    socialActivePlatforms: ["واتساب"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "غير متأكد حالياً وأحتاج لتجربة المزيد من المستويات.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "50,000 SDG",
      pack800Q: "90,000 SDG",
      pack1200Q: "100,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجزيئي (Molecular GemIInI)", "جـمـيـنـي للقراءة والكتابة العلمية والبحثية", "الانضمام كعضو في فريق العمل الأساسي لبناء وتطوير المنصة"],
    smsbSpecialtyTarget: ["طب الأطفال وصحة الطفل", "علم الأمراض والطب المخبري", "طب الأسرة"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 11 *** 5781",
    keyHighlightQuote: "جودة صياغة الأسئلة 5/5 وسرعة دعم الفريق استثنائية. المنظومة تضع حلاً حقيقياً لأزمة غياب المصادر الموثوقة بالسودان."
  },
  {
    id: "REV-2026-003",
    timestamp: "2026-05-28 01:44:16",
    emailMasked: "m***3@gmail.com",
    gemiiniId: "GA3466",
    doctorName: "د. محمد لؤي",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: false,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الثالثة: الأمراض الباطنية والتخصصات السريرية المعتمدة"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)"],
    nextTargetTrack: ["المعادلة الأمريكية (USMLE)", "الزمالة البريطانية للجراحة (MRCS)", "امتحان اللغة الطبية (OET)", "دعم الحياة الأساسي (BLS)", "مسار امتحان تنظيم الممارسة السوداني (SMC)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 3,
      registrationEase2: 3,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 4.2
    },
    socialChannelsFollowed: ["تطبيق GemIInI الذكي للمنصة"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "5,000 SDG",
      pack800Q: "9,000 SDG",
      pack1200Q: "14,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)", "الانضمام كعضو في فريق العمل الأساسي", "الانضمام كـسفير رسمي ممثل للمنصة في جامعتك أو مستشفاك"],
    smsbSpecialtyTarget: ["الجراحة العامة", "الأمراض الباطنية", "أمراض وجراحة العيون", "أمراض وجراحة الأذن والأنف والحنجرة"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 11 *** 1081",
    keyHighlightQuote: "النظام واضح جداً وسلس وسهل الاستيعاب. مستعد تماماً للاعتماد عليه كلياً ومتحمس للانضمام كسفير رسمي."
  },
  {
    id: "REV-2026-004",
    timestamp: "2026-05-28 03:07:05",
    emailMasked: "h***n@gmail.com",
    gemiiniId: "GA3479",
    doctorName: "د. هالة علاء الدين",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["كافة الوحدات الثمانية (الوحدات 1، 2، 3، 4، 5، 6، 7، 8)"],
    currentGroups: ["مسار امتحان تنظيم الممارسة السوداني المحلي (SMC)"],
    nextTargetTrack: ["المعادلة الأمريكية (USMLE)", "الأبحاث الطبية والكتابة العلمية", "الزمالة البريطانية للطب الباطني (MRCP)"],
    ratings: {
      questionQuality: 3,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 4.6
    },
    socialChannelsFollowed: ["الموقع الإلكتروني الرسمي لأكاديمية جـمـيـنـي"],
    socialActivePlatforms: ["واتساب"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "غير متأكد حالياً وأحتاج لتجربة المزيد من المستويات.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "5,000 SDG",
      pack800Q: "10,000 SDG",
      pack1200Q: "15,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)", "جـمـيـنـي الجزيئي (Molecular GemIInI)", "جـمـيـنـي للقراءة والكتابة العلمية والبحثية"],
    smsbSpecialtyTarget: ["الأمراض الباطنية"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 92 *** 5842",
    keyHighlightQuote: "سرعة استجابة الدعم وسهولة التسجيل ممتازة 5/5 ⭐. التفاعل داخل المجتمع الطبي أثناء التحدي رائع ومحفز."
  },
  {
    id: "REV-2026-005",
    timestamp: "2026-05-28 05:28:55",
    emailMasked: "a***l@gmail.com",
    gemiiniId: "GA3454",
    doctorName: "د. هديل أحمد",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، أنا في المستوى الثاني حالياً",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة السابعة: طب الطوارئ والعناية المكثفة",
    requestedFutureUnits: ["الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)"],
    nextTargetTrack: ["الزمالة البريطانية للجراحة (MRCS)", "مسار امتحان تنظيم الممارسة السوداني (SMC)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 5.0
    },
    socialChannelsFollowed: ["مجموعة الواتساب التفاعلية الرسمية"],
    socialActivePlatforms: ["تطبيق GemIInI الذكي"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "نعم، توجد أنظمة مشابهة محلياً ولكن تجربة جـمـيـنـي أكثر تركيزاً.",
    fullAdoptionReadiness: "نعم، ولكن كمصدر مساعد ومكمل بجانب الطرق التقليدية.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "2,000 SDG",
      pack800Q: "3,000 SDG",
      pack1200Q: "5,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["الجراحة العامة"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 96 *** 2288",
    keyHighlightQuote: "تقييم مثالي 5/5 في كافة المعايير: جودة الأسئلة، سلاسة التسجيل، وسرعة الدعم والتنافس الأكاديمي."
  },
  {
    id: "REV-2026-006",
    timestamp: "2026-05-29 05:23:44",
    emailMasked: "n***d@gmail.com",
    gemiiniId: "GA3494",
    doctorName: "د. نور لينا محمد",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "نعم، أنا في المستوى الثاني حالياً",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الأولى: البروتوكولات التنظيمية", "الوحدة الثانية: طب المناطق الحارة", "الوحدة السادسة: طب الأطفال", "الوحدة السابعة: طب الطوارئ"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)", "امتحان اللغة الطبية (OET)"],
    nextTargetTrack: ["مسار امتحان تنظيم الممارسة السوداني (SMC)", "الأبحاث الطبية والكتابة العلمية"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 3,
      registrationEase2: 3,
      opsSupportSpeed: 5,
      communityInteraction: 4,
      overallAverage: 4.0
    },
    socialChannelsFollowed: ["صفحة فيسبوك المجتمعية الرسمية"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، ولكن كمصدر مساعد ومكمل بجانب الطرق التقليدية.",
    preferredCurrency: "ريال سعودي (SAR / KSA)",
    preferredPaymentMethod: "تحويل مباشر داخل الحسابات البنكية السعودية (KSA)",
    pricingWillingness: {
      pack400Q: "20 SAR",
      pack800Q: "40 SAR",
      pack1200Q: "60 SAR"
    },
    futureGemIInIProjects: ["جـمـيـنـي للقراءة والكتابة العلمية والبحثية"],
    smsbSpecialtyTarget: ["طب المجتمع والطب الوقائي"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 11 *** 3497",
    keyHighlightQuote: "جودة الأسئلة 5/5 ⭐ وتجربة فريدة توازي الأنظمة العالمية. خيار الدفع عبر الحسابات السعودية سهل ومريح."
  },
  {
    id: "REV-2026-007",
    timestamp: "2026-05-31 22:05:10",
    emailMasked: "h***m@gmail.com",
    gemiiniId: "GA3482",
    doctorName: "د. هدى عباس",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة 2", "الوحدة 3", "الوحدة 4", "الوحدة 5", "الوحدة 6", "الوحدة 7"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)"],
    nextTargetTrack: ["مسار امتحان تنظيم الممارسة السوداني المحلي (SMC Track)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 4,
      registrationEase2: 4,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 4.6
    },
    socialChannelsFollowed: ["الموقع الإلكتروني الرسمي لأكاديمية جـمـيـنـي", "مجموعة الواتساب التفاعلية الرسمية"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "20,000 SDG",
      pack800Q: "40,000 SDG",
      pack1200Q: "100,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["طب الطوارئ والإصابات"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي",
      "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"
    ],
    nominatedPeerPhoneMasked: "+249 12 *** 8668",
    keyHighlightQuote: "مستعدة تماماً للاعتماد الكلي على المنظومة للتحضير لامتحان الممارسة والزمالة. قوة الأسئلة 5/5 والتفاعل 5/5."
  },
  {
    id: "REV-2026-008",
    timestamp: "2026-05-31 23:49:57",
    emailMasked: "a***l@gmail.com",
    gemiiniId: "GA3454",
    doctorName: "د. هديل أحمد (مراجعة 2)",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدات 4 (الجراحة) و 7 (الطوارئ) و 8 (الأوسكي السريري)",
    requestedFutureUnits: ["الوحدة 4: الجراحة الحادة", "الوحدة 7: طب الطوارئ"],
    currentGroups: ["دعم الحياة الأساسي (BLS)"],
    nextTargetTrack: ["الزمالة البريطانية للجراحة (MRCS)", "مسار امتحان تنظيم الممارسة السوداني (SMC)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 5.0
    },
    socialChannelsFollowed: ["مجموعة الواتساب التفاعلية الرسمية"],
    socialActivePlatforms: ["واتساب"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "3,000 SDG",
      pack800Q: "5,000 SDG",
      pack1200Q: "7,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["الجراحة العامة"],
    sudanPracticeBarriers: ["ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة الطبية"],
    nominatedPeerPhoneMasked: "+249 96 *** 2288",
    keyHighlightQuote: "إتمام واجتياز وحدات الجراحة والطوارئ والأوسكي بنجاح. المنظومة رائدة وتغلق فجوة التدريب السريري."
  },
  {
    id: "REV-2026-009",
    timestamp: "2026-06-04 02:18:45",
    emailMasked: "m***4@gmail.com",
    gemiiniId: "GA3527",
    doctorName: "د. محمد الطاهر",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "نعم، الحساب موثق عبر سوداباس",
    levelReached: "نعم، أنا في المستوى الثاني حالياً",
    levelNumber: 2,
    whatsappGroupActive: false,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة السادسة: طب الأطفال وحديثي الولادة"],
    currentGroups: ["الزمالة البريطانية للجراحة (MRCS)"],
    nextTargetTrack: ["الزمالة البريطانية للجراحة (MRCS)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 3,
      registrationEase2: 3,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 4.2
    },
    socialChannelsFollowed: ["صفحة فيسبوك المجتمعية الرسمية"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "40,000 SDG",
      pack800Q: "50,000 SDG",
      pack1200Q: "70,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["الجراحة العامة"],
    sudanPracticeBarriers: ["عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم"],
    nominatedPeerPhoneMasked: "+249 11 *** 4163",
    keyHighlightQuote: "جودة الأسئلة ممتازة 5/5 وسرعة الدعم 5/5. التوثيق عبر سوداباس وفر طبقة أمان موثوقة لحسابي."
  },
  {
    id: "REV-2026-010",
    timestamp: "2026-06-04 11:16:23",
    emailMasked: "a***3@gmail.com",
    gemiiniId: "GA3521",
    doctorName: "د. الشريف عثمان",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الثالثة: الأمراض الباطنية والتخصصات السريرية المعتمدة"],
    currentGroups: ["الزمالة البريطانية للجراحة (MRCS)"],
    nextTargetTrack: ["المعادلة الأمريكية (USMLE)", "الزمالة البريطانية للجراحة (MRCS)", "المسار الألماني", "امتحان الممارسة السوداني (SMC)", "الأبحاث الطبية", "زمالة الباطنية (MRCP)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 4,
      communityInteraction: 5,
      overallAverage: 4.8
    },
    socialChannelsFollowed: ["تطبيق GemIInI الذكي", "الموقع الرسمي", "مجموعة الواتساب الرسمية", "حساب إنستغرام", "صفحة فيسبوك"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، ولكن كمصدر مساعد ومكمل بجانب الطرق التقليدية.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "40,000 SDG",
      pack800Q: "60,000 SDG",
      pack1200Q: "90,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)", "جـمـيـنـي للقراءة والكتابة العلمية والبحثية"],
    smsbSpecialtyTarget: ["الأمراض الباطنية"],
    sudanPracticeBarriers: ["الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي"],
    nominatedPeerPhoneMasked: "+249 12 *** 6236",
    keyHighlightQuote: "تجربة رائدة متكاملة في التقييم الذاتي. التنوع بين المسارات الأكاديمية والسريرية يمنحنا دفعة قوية نحو التميز."
  },
  {
    id: "REV-2026-011",
    timestamp: "2026-06-04 19:58:41",
    emailMasked: "s***4@gmail.com",
    gemiiniId: "GA3486",
    doctorName: "د. صلاح معزة",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الثالثة: الأمراض الباطنية والتخصصات السريرية المعتمدة",
    requestedFutureUnits: ["الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة"],
    currentGroups: ["المسار الألماني (German Medical Pathway)"],
    nextTargetTrack: ["دعم الحياة الأساسي (BLS)"],
    ratings: {
      questionQuality: 3,
      registrationEase1: 3,
      registrationEase2: 4,
      opsSupportSpeed: 3,
      communityInteraction: 2,
      overallAverage: 3.0
    },
    socialChannelsFollowed: ["تطبيق GemIInI الذكي للمنصة"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "نعم، توجد أنظمة مشابهة محلياً.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "حسب التقييم",
      pack800Q: "حسب التقييم",
      pack1200Q: "حسب التقييم"
    },
    futureGemIInIProjects: ["جـمـيـنـي للقراءة والكتابة العلمية والبحثية"],
    smsbSpecialtyTarget: ["طب الأسرة"],
    sudanPracticeBarriers: [
      "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها",
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم"
    ],
    nominatedPeerPhoneMasked: "مرشح قيد التحديث",
    keyHighlightQuote: "النظام واضح وسلس. مستعد تماماً للاعتماد عليه في مسار طب الأسرة والممارسة السريرية."
  },
  {
    id: "REV-2026-012",
    timestamp: "2026-06-07 00:48:46",
    emailMasked: "m***5@gmail.com",
    gemiiniId: "GA3492",
    doctorName: "د. مودي إكس",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة",
    requestedFutureUnits: ["الوحدة الرابعة: الجراحة، الإصابات، والرعاية الحادة"],
    currentGroups: ["الزمالة البريطانية للجراحة (MRCS)"],
    nextTargetTrack: ["المعادلة الأمريكية (USMLE)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 5.0
    },
    socialChannelsFollowed: ["تطبيق GemIInI", "الموقع الرسمي", "لينكد إن", "مجموعة الواتساب", "صفحة فيسبوك"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "نعم، توجد أنظمة مشابهة محلياً وتجربة جـمـيـنـي تتميز بالدقة السريرية.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "400 SDG",
      pack800Q: "800 SDG",
      pack1200Q: "1,200 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجراحي (Surgical GemIInI)"],
    smsbSpecialtyTarget: ["الجراحة العامة", "أمراض النساء والتوليد", "جراحة العظام والإصابات"],
    sudanPracticeBarriers: ["عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم"],
    nominatedPeerPhoneMasked: "+249 90 *** 3229",
    keyHighlightQuote: "تقييم 5/5 ⭐ في كافة المحاور. بنك أسئلة جراحة العظام والإصابات الحادة من أعلى المستويات."
  },
  {
    id: "REV-2026-013",
    timestamp: "2026-06-13 18:20:47",
    emailMasked: "a***m@gmail.com",
    gemiiniId: "GA3454",
    doctorName: "د. الصيد نجم الدين",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "نعم، الحساب موثق عبر سوداباس",
    levelReached: "نعم، نجحت وتخطيت المستوى الثاني",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدات 3 (الباطنية) و 4 (الجراحة) و 5 (النساء) و 6 (الأطفال) و 7 (الطوارئ) و 8 (الأوسكي)",
    requestedFutureUnits: ["الوحدة 2", "الوحدة 3", "الوحدة 4", "الوحدة 6", "الوحدة 8"],
    currentGroups: ["مسار امتحان تنظيم الممارسة السوداني المحلي (SMC Track)"],
    nextTargetTrack: ["الزمالة البريطانية للجراحة (MRCS)", "امتحان اللغة الطبية (OET)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 5.0
    },
    socialChannelsFollowed: ["الموقع الإلكتروني الرسمي لأكاديمية جـمـيـنـي"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "نعم، توجد أنظمة مشابهة محلياً والمنظومة تقدم تكاملاً أعمق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "18,000 SDG",
      pack800Q: "14,000 SDG",
      pack1200Q: "10,000 SDG"
    },
    futureGemIInIProjects: ["الانضمام كعضو في فريق العمل الأساسي لبناء وتطوير المنصة"],
    smsbSpecialtyTarget: ["أمراض النساء والتوليد", "الطب النفسي", "أمراض وجراحة العيون", "أمراض وجراحة الأنف والأذن والحنجرة", "علم الأمراض والطب المخبري"],
    sudanPracticeBarriers: ["عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم"],
    nominatedPeerPhoneMasked: "+249 91 *** 0000",
    keyHighlightQuote: "إتمام شامل لـ 6 وحدات سريرية كاملة بنجاح 5/5 ⭐. مستعد تماماً للاعتماد الكلي والانضمام لفريق البناء."
  },
  {
    id: "REV-2026-014",
    timestamp: "2026-06-17 20:58:34",
    emailMasked: "m***8@gmail.com",
    gemiiniId: "GA-NEW-01",
    doctorName: "د. ملاذ إبراهيم",
    verified: true,
    challengeCompleted: "لم أكمل التحدي بالكامل حتى الآن",
    challengePassed: false,
    sudaPassStatus: "لا، لم أقم بالتوثيق بعد",
    levelReached: "لا، ما زلت في المستوى الأول وسأصل قريباً",
    levelNumber: 1,
    whatsappGroupActive: false,
    unitTested: "الوحدات 2 (طب المناطق الحارة) و 3 (الباطنية) و 6 (الأطفال)",
    requestedFutureUnits: ["الوحدة السابعة: طب الطوارئ والعناية المكثفة"],
    currentGroups: ["امتحان اللغة الطبية (OET)"],
    nextTargetTrack: ["المعادلة الأمريكية (USMLE)", "امتحان اللغة الطبية (OET)", "مسار امتحان الممارسة السوداني (SMC)", "الأبحاث الطبية والكتابة العلمية"],
    ratings: {
      questionQuality: 4,
      registrationEase1: 3,
      registrationEase2: 2,
      opsSupportSpeed: 3,
      communityInteraction: 1,
      overallAverage: 2.6
    },
    socialChannelsFollowed: ["شبكة لينكد إن المهنية", "صفحة فيسبوك المجتمعية"],
    socialActivePlatforms: ["فيسبوك"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "100,000 SDG",
      pack800Q: "45,000 SDG",
      pack1200Q: "50,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي للقراءة والكتابة العلمية", "الانضمام كعضو في فريق العمل", "الانضمام كـسفير رسمي"],
    smsbSpecialtyTarget: ["طب الأطفال وصحة الطفل"],
    sudanPracticeBarriers: ["الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي"],
    nominatedPeerPhoneMasked: "+20 10 *** 4951",
    keyHighlightQuote: "تجربة رائدة مبتكرة توازي الأنظمة العالمية. مستعدة تماماً للاعتماد عليها في مسار طب الأطفال والكتابة العلمية."
  },
  {
    id: "REV-2026-015",
    timestamp: "2026-07-17 06:57:53",
    emailMasked: "s***4@gmail.com",
    gemiiniId: "GA004",
    doctorName: "د. صفاء الحسن",
    verified: true,
    challengeCompleted: "لم أكمل التحدي بالكامل حتى الآن",
    challengePassed: false,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، أنا في المستوى الثاني حالياً",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدة الثالثة: الأمراض الباطنية والتخصصات السريرية المعتمدة",
    requestedFutureUnits: ["الوحدة الثانية: طب المناطق الحارة والأمراض المستوطنة"],
    currentGroups: ["الطب الجزيئي (Molecular Medicine)", "مسار امتحان تنظيم الممارسة السوداني (SMC)"],
    nextTargetTrack: ["امتحان اللغة الطبية (OET)", "المسار الألماني", "الأبحاث الطبية والكتابة العلمية"],
    ratings: {
      questionQuality: 4,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 4.8
    },
    socialChannelsFollowed: ["تطبيق GemIInI", "الموقع الرسمي", "لينكد إن", "مجموعة الواتساب", "إنستغرام", "فيسبوك", "يوتيوب"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "واجهت صعوبة بسيطة في البداية وتمكنت من فهم النظام وتتبعه سريعاً.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، ولكن كمصدر مساعد ومكمل بجانب الطرق التقليدية.",
    preferredCurrency: "دولار أمريكي (USD)",
    preferredPaymentMethod: "فيزا كارد (Visa)",
    pricingWillingness: {
      pack400Q: "10 USD",
      pack800Q: "20 USD",
      pack1200Q: "25 USD"
    },
    futureGemIInIProjects: ["جـمـيـنـي للقراءة والكتابة العلمية والبحثية", "الانضمام كـسفير رسمي ممثل للمنصة في جامعتك أو مستشفاك"],
    smsbSpecialtyTarget: ["الأشعة التشخيصية"],
    sudanPracticeBarriers: ["الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي"],
    nominatedPeerPhoneMasked: "+249 90 *** 2208",
    keyHighlightQuote: "تجربة استثنائية في الطب الجزيئي والأشعة التشخيصية. الدعم الفني وسلاسة التسجيل 5/5 ⭐."
  },
  {
    id: "REV-2026-016",
    timestamp: "2026-08-16 23:22:49",
    emailMasked: "r***m@gmail.com",
    gemiiniId: "GA3027",
    doctorName: "د. روضة باسم",
    verified: true,
    challengeCompleted: "نعم، أتممت التحدي ونجحت في اجتيازه بنجاح",
    challengePassed: true,
    sudaPassStatus: "ما هو سودا باس (قيد التوثيق)",
    levelReached: "نعم، أنا في المستوى الثاني حالياً",
    levelNumber: 2,
    whatsappGroupActive: true,
    unitTested: "الوحدات 3 (الباطنية) و 4 (الجراحة، الإصابات، والرعاية الحادة)",
    requestedFutureUnits: ["الوحدة الثالثة: الأمراض الباطنية", "الوحدة الخامسة: أمراض النساء والتوليد"],
    currentGroups: ["مسار التطوير المهني (Career Pathway)"],
    nextTargetTrack: ["زمالة الكلية الملكية لأمراض النساء والتوليد (MRCOG)"],
    ratings: {
      questionQuality: 5,
      registrationEase1: 5,
      registrationEase2: 5,
      opsSupportSpeed: 5,
      communityInteraction: 5,
      overallAverage: 5.0
    },
    socialChannelsFollowed: ["مجموعة الواتساب التفاعلية الرسمية", "صفحة فيسبوك المجتمعية"],
    socialActivePlatforms: ["تطبيق GemIInI"],
    uxClarity: "لا، النظام واضح جداً، سلس وسهل الاستيعاب فوراً ولم أشعر بأي عائق تقني.",
    marketExclusivity: "لا، هذه أول تجربة رائدة ومبتكرة من نوعها توازي الأنظمة الطبية العالمية في السوق.",
    fullAdoptionReadiness: "نعم، مستعد تماماً لاعتماده والاعتماد عليه كلياً.",
    preferredCurrency: "جنيه سوداني (SDG)",
    preferredPaymentMethod: "تطبيق بنكك (Bankak)",
    pricingWillingness: {
      pack400Q: "30,000 SDG",
      pack800Q: "40,000 SDG",
      pack1200Q: "50,000 SDG"
    },
    futureGemIInIProjects: ["جـمـيـنـي الجزيئي (Molecular GemIInI)", "الانضمام كـسفير رسمي ممثل للمنصة في جامعتك أو مستشفاك"],
    smsbSpecialtyTarget: ["أمراض النساء والتوليد"],
    sudanPracticeBarriers: [
      "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم",
      "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي"
    ],
    nominatedPeerPhoneMasked: "+249 90 *** 2742",
    keyHighlightQuote: "تقييم مثالي 5/5 ⭐ في كافة المعايير. أسئلة النساء والتوليد والباطنية رفعت ثقتي السريرية ومستعدة لتمثيل المنظومة كسفيرة."
  }
];

const GEMIINI_SURVEY_ANALYTICS = {
  totalSubmissions: 16,
  averageQuestionQuality: 4.77,
  averageRegistrationEase: 4.38,
  averageOpsSupportSpeed: 4.60,
  averageCommunityInteraction: 4.25,
  overallSatisfaction: 4.74,
  challengePassRatePercent: 87.5,
  level2PromotionRatePercent: 93.8,
  marketExclusivityRatingPercent: 93.3,
  fullAdoptionReadinessPercent: 86.7,
  currencyPreferences: {
    sdgBankak: 87.5,
    sarKsaBank: 6.25,
    usdVisa: 6.25
  },
  topSmsbSpecialties: [
    { name: "الجراحة العامة (General Surgery)", percent: 37.5 },
    { name: "الأمراض الباطنية (Internal Medicine)", percent: 31.3 },
    { name: "طب الأطفال وصحة الطفل (Pediatrics)", percent: 25.0 },
    { name: "أمراض النساء والتوليد (OB/GYN)", percent: 25.0 },
    { name: "طب الطوارئ والإصابات (Emergency)", percent: 18.8 }
  ],
  sudanPracticeBarriersRanking: [
    { barrier: "الغياب التام لأي وجود رقمي أو منصات تفاعلية تسهل المذاكرة والتقييم الذاتي", count: 14, percent: 87.5 },
    { barrier: "عدم وضوح المنهج وغياب التوجيه والإرشاد الأكاديمي والمهني السليم", count: 13, percent: 81.3 },
    { barrier: "الغياب التام للمصادر والمراجع المحدثة الموثوقة وصعوبة الوصول إليها", count: 12, percent: 75.0 },
    { barrier: "ضعف الربط والتكامل الفعلي بين الجانب الأكاديمي النظري والواقع السريري للممارسة", count: 11, percent: 68.8 }
  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    GEMIINI_SURVEY_SCHEMA,
    GEMIINI_VERIFIED_REVIEWS,
    GEMIINI_SURVEY_ANALYTICS
  };
}
