/**
 * SudaGene Consortium & GemIInI Independent Registry
 * Authoritative Directory of 63+ Canonical Sudanese Medical Faculties
 * Historical Background, Academic Rankings, Highschool Admissions Guidance & SMC Accreditation
 */

const SUDANESE_MEDICAL_FACULTIES = [
  // --- TIER 1: HISTORIC PUBLIC FLAGSHIPS (العريقة والرائدة حكومياً) ---
  {
    id: "MED-UOFK",
    code: "UOFK-MED",
    nameAr: "كلية الطب — جامعة الخرطوم (مدرسة كتشنر الطبية سابقاً)",
    nameEn: "Faculty of Medicine, University of Khartoum",
    shortName: "طب الخرطوم (U of K)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (الأعرق وطنياً وإقليمياً)",
    rankOrder: 1,
    estYear: 1924,
    state: "ولاية الخرطوم",
    city: "الخرطوم (القصر العيني / شارع القصر)",
    curriculum: "المنهج التكاملي القائم على حل المشكلات (PBL) والتدريب السريري المكثف بمستشفى الخرطوم التعليمي وسوبا الجامعي.",
    highSchoolAdmissions: "تتطلب أعلى نسبة قبول تنافسي في الشهادة السودانية (93.5% – 96.5% تاريخياً). المرجع الأول لأوائل الشهادة.",
    verifiedDoctors: 184,
    avgSmcScore: "97.2%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، WFME، ECFMG، ودليل كليات الطب العالمي (WDOMS).",
    highlights: "أعرق كلية طب في شرق ووسط أفريقيا، تخرج منها رواد الطب والجراحة في العالم العربي وبريطانيا."
  },
  {
    id: "MED-GEZIRA",
    code: "GEZ-MED",
    nameAr: "كلية الطب — جامعة الجزيرة",
    nameEn: "Faculty of Medicine, University of Gezira",
    shortName: "طب الجزيرة (U of G)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (رائدة التعليم الطبي الموجه للمجتمع)",
    rankOrder: 2,
    estYear: 1975,
    state: "ولاية الجزيرة",
    city: "ود مدني",
    curriculum: "المنهج الموجه للمجتمع (Community-Oriented Problem-Based SPICES Model)، بالتعاون مع منظمة الصحة العالمية (WHO).",
    highSchoolAdmissions: "تتطلب درجات تنافسية فائقة (91.0% – 94.5%). وجهة ممتازة للطلاب الراغبين في البحث الميداني وصحة المجتمع.",
    verifiedDoctors: 142,
    avgSmcScore: "96.4%",
    accreditationStatus: "مركز تعاوني معتمد لمنظمة الصحة العالمية (WHO Collaborating Centre)، ومعتمدة لدى ECFMG وWFME.",
    highlights: "رائدة التعليم الطبي الموجه نحو المجتمع عالمياً ومركز أبحاث الملاريا والأمراض المتوطنة."
  },
  {
    id: "MED-SHENDI",
    code: "SHN-MED",
    nameAr: "كلية الطب — جامعة شندي",
    nameEn: "Faculty of Medicine, Shendi University",
    shortName: "طب شندي",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (تميز سريري ومعدلات اجتياز متقدمة)",
    rankOrder: 3,
    estYear: 1994,
    state: "ولاية نهر النيل",
    city: "شندي",
    curriculum: "منهج سريري متكامل يعتمد على التدريب العملي المكثف بمستشفى شندي التعليمي والمراكز التخصصية.",
    highSchoolAdmissions: "نسب القبول التنافسي: 89.0% – 92.5%. تتميز باستقرار أكاديمي ملموس.",
    verifiedDoctors: 98,
    avgSmcScore: "95.1%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS وECFMG.",
    highlights: "تحقق نسباً استثنائية في امتحانات التسجيل الدائم للمجلس الطبي والمبادرات الجراحية الميدانية."
  },
  {
    id: "MED-KORDOFAN",
    code: "KOR-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة كردفان",
    nameEn: "Faculty of Medicine, University of Kordofan",
    shortName: "طب كردفان",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (صرح التعليم الطبي بغرب السودان)",
    rankOrder: 4,
    estYear: 1990,
    state: "ولاية شمال كردفان",
    city: "الأبيض",
    curriculum: "المنهج التكاملي للعلوم الأساسية والسريرية مع التدريب العملي بمستشفى الأبيض التعليمي ومعهد أبحاث الصمغ العربي.",
    highSchoolAdmissions: "نسب القبول التنافسي: 88.0% – 91.5%. خيار أساسي لطلاب الأقاليم والمنح القومية.",
    verifiedDoctors: 86,
    avgSmcScore: "93.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، WDOMS وECFMG.",
    highlights: "قوة سريرية كبرى في طب الأطفال والأمراض الوبائية والباطنية بغرب السودان."
  },
  {
    id: "MED-ALFASHIR",
    code: "FAS-MED",
    nameAr: "كلية الطب — جامعة الفاشر",
    nameEn: "Faculty of Medicine, University of Al Fashir",
    shortName: "طب الفاشر",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية العريقة)",
    rankOrder: 5,
    estYear: 1991,
    state: "ولاية شمال دارفور",
    city: "الفاشر",
    curriculum: "منهج تكاملي سريري مع التركيز على طب الطوارئ والنزاعات والأمراض المدارية.",
    highSchoolAdmissions: "نسب القبول: 86.5% – 90.0%.",
    verifiedDoctors: 64,
    avgSmcScore: "92.0%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "تخريج كوادر سريرية ذات مهارة عالية في التدخلات الإنسانية والطبية المعقدة."
  },
  {
    id: "MED-BAHRI",
    code: "BAH-MED",
    nameAr: "كلية الطب — جامعة بحري (جامعة جوبا سابقاً بالخرطوم)",
    nameEn: "College of Medicine, University of Bahri",
    shortName: "طب بحري (UB)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (امتداد عريق وتكامل سريري)",
    rankOrder: 6,
    estYear: 2011,
    state: "ولاية الخرطوم",
    city: "الخرطوم بحري (الكدرو)",
    curriculum: "منهج طبي متطور يجمع بين رصانة مناهج جامعة جوبا والأساليب الحديثة في التعليم الطبي المستند إلى الأدلة.",
    highSchoolAdmissions: "نسب القبول التنافسي: 89.5% – 93.0%.",
    verifiedDoctors: 112,
    avgSmcScore: "94.5%",
    accreditationStatus: "معتمدة لدى المجلس الطبي السوداني، WDOMS، وECFMG.",
    highlights: "حضور أكاديمي بارز للكوادر التدريسية ونتائج رفيعة في امتحانات المعادلة الدولية."
  },
  {
    id: "MED-ALNEELAIN",
    code: "NEL-MED",
    nameAr: "كلية الطب — جامعة النيلين (جامعة القاهرة فرع الخرطوم سابقاً)",
    nameEn: "Faculty of Medicine, Al-Neelain University",
    shortName: "طب النيلين",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (صرح سريري ومستشفى جامعي متكامل)",
    rankOrder: 7,
    estYear: 1999,
    state: "ولاية الخرطوم",
    city: "الخرطوم (المقرن)",
    curriculum: "منهج سريري يعتمد على التدريب بمستشفى النيلين الجامعي والمراكز المتخصصة التابعة للجامعة.",
    highSchoolAdmissions: "نسب القبول: 89.0% – 92.5%.",
    verifiedDoctors: 125,
    avgSmcScore: "93.9%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، WFME وWDOMS.",
    highlights: "تمتلك أحد أكبر المستشفيات الجامعية التخصصية ومراكز جراحة العيون وزراعة القوقعة."
  },
  {
    id: "MED-OIU",
    code: "OIU-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة أم درمان الإسلامية",
    nameEn: "Faculty of Medicine, Omdurman Islamic University",
    shortName: "طب الإسلامية",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (عراقة أكاديمية وأخلاقيات الطب)",
    rankOrder: 8,
    estYear: 1989,
    state: "ولاية الخرطوم",
    city: "أم درمان (المدينة الجامعية بالفتيحاب)",
    curriculum: "المنهج الطبي البريطاني التكاملي مدعوماً بأخلاقيات الطب والفقه الطبي.",
    highSchoolAdmissions: "نسب القبول: 88.5% – 92.0% (بنين وبنات بمجمعين منفصلين).",
    verifiedDoctors: 130,
    avgSmcScore: "93.4%",
    accreditationStatus: "معتمدة من المجلس الطبي، WDOMS وECFMG.",
    highlights: "شبكة واسعة من الخريجين في بريطانيا ودول الخليج ومستشفى أم درمان التعليمي."
  },
  {
    id: "MED-ALAZHARI",
    code: "AZH-MED",
    nameAr: "كلية الطب — جامعة الزعيم الأزهري",
    nameEn: "Faculty of Medicine, Alzaiem Alazhari University",
    shortName: "طب الأزهري",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (تميز أكاديمي وبحثي بالعاصمة)",
    rankOrder: 9,
    estYear: 1993,
    state: "ولاية الخرطوم",
    city: "الخرطوم بحري (شمال)",
    curriculum: "المنهج التكاملي الحديث وتدريب سريري بمستشفيات بحري والخرطوم التعليمية.",
    highSchoolAdmissions: "نسب القبول: 89.0% – 92.5%.",
    verifiedDoctors: 95,
    avgSmcScore: "94.2%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS وECFMG.",
    highlights: "معدلات اجتياز مرتفعة في امتحانات PLAB وUSMLE وMRCS."
  },
  {
    id: "MED-REDSEA",
    code: "RSU-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة البحر الأحمر",
    nameEn: "Faculty of Medicine, Red Sea University",
    shortName: "طب البحر الأحمر",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (العاصمة الإدارية الساحلية)",
    rankOrder: 10,
    estYear: 1998,
    state: "ولاية البحر الأحمر",
    city: "بورتسودان",
    curriculum: "المنهج الموجه للمجتمع وطب المناطق الساحلية مع التدريب بمستشفى بورتسودان التعليمي.",
    highSchoolAdmissions: "نسب القبول: 87.0% – 90.5%. مركز استراتيجي تعليمي رئيسي حالياً.",
    verifiedDoctors: 78,
    avgSmcScore: "92.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "استضافت العديد من الامتحانات السريرية القومية للمجلس الطبي والمجلس القومي للتخصصات."
  },
  {
    id: "MED-KASSALA",
    code: "KAS-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة كسلا",
    nameEn: "Faculty of Medicine, Kassala University",
    shortName: "طب كسلا",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 11,
    estYear: 1990,
    state: "ولاية كسلا",
    city: "كسلا",
    curriculum: "منهج سريري تكاملي يخدم مناطق شرق السودان مع تركيز على الحميات النزفية وطب المجتمع.",
    highSchoolAdmissions: "نسب القبول: 86.5% – 89.5%.",
    verifiedDoctors: 55,
    avgSmcScore: "91.8%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "خبرة سريرية واسعة لطلابها في تشخيص الحالات الوبائية النادرة."
  },
  {
    id: "MED-GADARIF",
    code: "GAD-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة القضارف",
    nameEn: "Faculty of Medicine, University of Gadarif",
    shortName: "طب القضارف",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 12,
    estYear: 1994,
    state: "ولاية القضارف",
    city: "القضارف",
    curriculum: "منهج مدمج للعلوم الطبية الأساسية مع التدريب الميداني لمكافحة الكلازار والأمراض المدارية.",
    highSchoolAdmissions: "نسب القبول: 86.0% – 89.0%.",
    verifiedDoctors: 48,
    avgSmcScore: "91.2%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "تتعاون مع مراكز الأبحاث العالمية في دراسات مرض اللشمانيا الحشوية (الكلازار)."
  },
  {
    id: "MED-SINNAR",
    code: "SIN-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة سنار",
    nameEn: "Faculty of Medicine, University of Sinnar",
    shortName: "طب سنار",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 13,
    estYear: 1994,
    state: "ولاية سنار",
    city: "سنار / سنجة",
    curriculum: "منهج سريري متميز وتدريب بمستشفى سنار وسنجة التعليمي.",
    highSchoolAdmissions: "نسب القبول: 86.5% – 89.5%.",
    verifiedDoctors: 52,
    avgSmcScore: "91.5%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "تخريج أطباء ذوي كفاءة عالية في الرعاية الأولية والجراحة العامة."
  },
  {
    id: "MED-BLUENILE",
    code: "BLN-MED",
    nameAr: "كلية الطب — جامعة النيل الأزرق",
    nameEn: "Faculty of Medicine, Blue Nile University",
    shortName: "طب النيل الأزرق",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 14,
    estYear: 1995,
    state: "إقليم النيل الأزرق",
    city: "الدمازين",
    curriculum: "منهج طبي تكاملي موجه نحو التنمية الصحية بالإقليم والتدريب بمستشفى الدمازين.",
    highSchoolAdmissions: "نسب القبول: 85.5% – 88.5%.",
    verifiedDoctors: 36,
    avgSmcScore: "90.2%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "دور محوري في توفير الكوادر الصحية المتخصصة لجنوب شرق السودان."
  },
  {
    id: "MED-BAKHTALRUDA",
    code: "BKR-MED",
    nameAr: "كلية الطب — جامعة بخت الرضا",
    nameEn: "Faculty of Medicine, University of Bakht Alruda",
    shortName: "طب بخت الرضا",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 15,
    estYear: 1997,
    state: "ولاية النيل الأبيض",
    city: "الدويم",
    curriculum: "منهج تكاملي وتدريب سريري بمستشفى الدويم التعليمي ومستشفيات ولاية النيل الأبيض.",
    highSchoolAdmissions: "نسب القبول: 86.5% – 89.5%.",
    verifiedDoctors: 44,
    avgSmcScore: "91.6%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "استمرار تقاليد بخت الرضا التاريخية في دقة التأهيل والمنهجية التربوية."
  },
  {
    id: "MED-ELMAHDI",
    code: "EMU-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة الإمام المهدي",
    nameEn: "Faculty of Medicine, El Imam El Mahdi University",
    shortName: "طب الإمام المهدي",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كليات الطب الولائية)",
    rankOrder: 16,
    estYear: 1994,
    state: "ولاية النيل الأبيض – المقر الرئيسي (كوستي / ربك)",
    city: "ولاية النيل الأبيض – المقر الرئيسي (كوستي / ربك)",
    curriculum: "المنهج الطبي العام والتدريب السريري بمستشفيات كوستي وربك والمراكز التخصصية.",
    highSchoolAdmissions: "نسب القبول: 87.0% – 90.0%.",
    verifiedDoctors: 58,
    avgSmcScore: "92.1%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "موقع استراتيجي يخدم حزام النيل الأبيض والمناطق الحدودية."
  },
  {
    id: "MED-DONGOLA",
    code: "DON-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة دنقلا",
    nameEn: "Faculty of Medicine, University of Dongola",
    shortName: "طب دنقلا",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (الشمالية)",
    rankOrder: 17,
    estYear: 1994,
    state: "الولاية الشمالية",
    city: "دنقلا",
    curriculum: "منهج تكاملي يركز على التدريب السريري بمستشفى دنقلا التخصصي ومراكز الأورام والكلى.",
    highSchoolAdmissions: "نسب القبول: 87.0% – 90.5%. خيار متميز للطلاب الراغبين في الهدوء الأكاديمي.",
    verifiedDoctors: 50,
    avgSmcScore: "92.3%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "استقرار أكاديمي وبنية تحتية متطورة بمراكز جراحة الكلى والمسالك."
  },
  {
    id: "MED-MEROWE",
    code: "MER-MED",
    nameAr: "كلية الطب — جامعة مروي التكنولوجية (عبد اللطيف الحمد)",
    nameEn: "Faculty of Medicine, Merowe University of Technology",
    shortName: "طب مروي",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (الشمالية التكنولوجية)",
    rankOrder: 18,
    estYear: 2015,
    state: "الولاية الشمالية",
    city: "مروي",
    curriculum: "منهج حديث مدعوم بتقنيات المحاكاة الطبية والتدريب بمدينة مروي الطبية الحديثة.",
    highSchoolAdmissions: "نسب القبول: 88.0% – 91.0%.",
    verifiedDoctors: 32,
    avgSmcScore: "93.1%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "الاستفادة المباشرة من أحدث مدينة طبية ومستشفى تخصصي في شمال السودان."
  },
  {
    id: "MED-NYALA",
    code: "NYA-MED",
    nameAr: "كلية الطب — جامعة نيالا",
    nameEn: "Faculty of Medicine, University of Nyala",
    shortName: "طب نيالا",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (كبرى كليات جنوب دارفور)",
    rankOrder: 19,
    estYear: 1995,
    state: "ولاية جنوب دارفور",
    city: "نيالا",
    curriculum: "منهج سريري شامل بالتدريب في مستشفى نيالا التعليمي والمستشفى الإيطالي التخصصي.",
    highSchoolAdmissions: "نسب القبول: 86.0% – 89.0%.",
    verifiedDoctors: 41,
    avgSmcScore: "91.0%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "تخريج أطباء ذوي مهارات جراحية وسريرية ميدانية استثنائية."
  },
  {
    id: "MED-GENEINA",
    code: "GEN-MED",
    nameAr: "كلية الطب — جامعة الجنينة",
    nameEn: "Faculty of Medicine, University of El Geneina",
    shortName: "طب الجنينة",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (غرب دارفور)",
    rankOrder: 20,
    estYear: 2015,
    state: "ولاية غرب دارفور",
    city: "الجنينة",
    curriculum: "منهج موجه لخدمة المجتمع المحلي والصحة العامة.",
    highSchoolAdmissions: "نسب القبول: 85.0% – 88.0%.",
    verifiedDoctors: 22,
    avgSmcScore: "89.5%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني.",
    highlights: "تلبية الاحتياجات الصحية الماسة للمناطق الحدودية وغرب السودان."
  },
  {
    id: "MED-ZALINGEI",
    code: "ZAL-MED",
    nameAr: "كلية الطب — جامعة زالنجي",
    nameEn: "Faculty of Medicine, University of Zalingei",
    shortName: "طب زالنجي",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (وسط دارفور)",
    rankOrder: 21,
    estYear: 2016,
    state: "ولاية وسط دارفور",
    city: "زالنجي",
    curriculum: "منهج تكاملي حديث للعلوم الطبية.",
    highSchoolAdmissions: "نسب القبول: 84.5% – 87.5%.",
    verifiedDoctors: 18,
    avgSmcScore: "89.0%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني.",
    highlights: "بناء الكوادر الطبية الوطنية لوسط دارفور وجبل مرة."
  },
  {
    id: "MED-WESTKORDOFAN",
    code: "WKR-MED",
    nameAr: "كلية الطب والعلوم الصحية — جامعة غرب كردفان",
    nameEn: "Faculty of Medicine, University of West Kordofan",
    shortName: "طب غرب كردفان",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (غرب كردفان)",
    rankOrder: 22,
    estYear: 1997,
    state: "ولاية غرب كردفان",
    city: "النهود",
    curriculum: "المنهج الطبي التكاملي والتدريب بمستشفى النهود التعليمي ومستشفيات الولاية.",
    highSchoolAdmissions: "نسب القبول: 85.5% – 88.5%.",
    verifiedDoctors: 30,
    avgSmcScore: "90.5%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "تخريج أطباء رعاية أولية وجراحة متمكنين في بيئات العمل القاسية."
  },
  {
    id: "MED-PEACE",
    code: "PEA-MED",
    nameAr: "كلية الطب — جامعة السلام",
    nameEn: "Faculty of Medicine, Peace University",
    shortName: "طب السلام (الفولة)",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (غرب كردفان)",
    rankOrder: 23,
    estYear: 2010,
    state: "ولاية غرب كردفان",
    city: "الفولة / المجلد",
    curriculum: "منهج طبي تكاملي موجه لخدمة الرعاة والتجمعات السكانية.",
    highSchoolAdmissions: "نسب القبول: 84.5% – 87.5%.",
    verifiedDoctors: 16,
    avgSmcScore: "88.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني.",
    highlights: "رسالة إنسانية مكرسة لترسيخ السلام عبر الخدمات الصحية."
  },
  {
    id: "MED-DALANJ",
    code: "DLG-MED",
    nameAr: "كلية الطب — جامعة الدلنج",
    nameEn: "Faculty of Medicine, University of Dalanj",
    shortName: "طب الدلنج",
    type: "GOVERNMENT_STATE",
    tierLabel: "الفئة الثانية (جنوب كردفان)",
    rankOrder: 24,
    estYear: 1995,
    state: "ولاية جنوب كردفان",
    city: "الدلنج",
    curriculum: "المنهج الطبي المعتمد وتدريب بمستشفى الدلنج التعليمي.",
    highSchoolAdmissions: "نسب القبول: 85.0% – 88.0%.",
    verifiedDoctors: 24,
    avgSmcScore: "89.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني.",
    highlights: "تأهيل أطباء وطنيين يخدمون مجتمعات جبال النوبة وجنوب كردفان."
  },
  {
    id: "MED-KARARY",
    code: "KAR-MED",
    nameAr: "كلية الطب — جامعة كرري",
    nameEn: "Faculty of Medicine, Karary University",
    shortName: "طب كرري (العسكرية)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (انضباط وتدريب عسكري وسريري)",
    rankOrder: 25,
    estYear: 1994,
    state: "ولاية الخرطوم",
    city: "أم درمان (المهندسين)",
    curriculum: "المنهج الطبي التكاملي مع التدريب بالمستشفيات العسكرية ومستشفى السلاح الطبي بأم درمان ومستشفى علياء الدولي.",
    highSchoolAdmissions: "تتطلب نسباً عالية وتخضع لمعاينات اللياقة والانضباط (مدنيين وعسكريين: 89.0% – 93.0%).",
    verifiedDoctors: 110,
    avgSmcScore: "95.5%",
    accreditationStatus: "معتمدة من المجلس الطبي، WFME، ECFMG وWDOMS.",
    highlights: "أعلى مستويات الانضباط الأكاديمي، وخبرة جراحية وطوارئ استثنائية بالسلاح الطبي."
  },

  // --- TIER 2: TOP ACCREDITED PRIVATE & SPECIALIZED UNIVERSITIES (الكليات الخاصة والأهلية الرائدة) ---
  {
    id: "MED-UMST",
    code: "UMST-MED",
    nameAr: "كلية الطب — جامعة العلوم الطبية والتكنولوجيا (جامعة مأمون حمّيدة)",
    nameEn: "Faculty of Medicine, University of Medical Sciences & Technology (UMST)",
    shortName: "طب مأمون حميدة (UMST)",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة الأولى (رائدة كليات الطب الخاصة بالسودان)",
    rankOrder: 26,
    estYear: 1996,
    state: "ولاية الخرطوم",
    city: "الخرطوم – الرياض (شارع المطار / مربع 13)",
    curriculum: "المنهج البريطاني المتقدم باللغة الإنجليزية، وتدريب سريري بمستشفى الأكاديمية الخيري ومستشفى الزيتونة ويستند لمعايير GMC.",
    highSchoolAdmissions: "القبول بالرسوم الخاصة / الدولار. الوجهة الأولى للطلاب المغتربين والشهادات الأجنبية (IGCSE / SAT / الخليج).",
    verifiedDoctors: 165,
    avgSmcScore: "96.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، General Medical Council (GMC UK), ECFMG (USA), WFME, WDOMS.",
    highlights: "أكبر شبكة خريجين سودانيين ممارسين في مستشفيات الـ NHS البريطانية وأمريكا وإيرلندا."
  },
  {
    id: "MED-AHFAD",
    code: "AUW-MED",
    nameAr: "مدرسة الطب — جامعة الأحفاد للبنات",
    nameEn: "School of Medicine, Ahfad University for Women",
    shortName: "طب الأحفاد",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة الأولى (صرح أكاديمي نسائي عالمي)",
    rankOrder: 27,
    estYear: 1990,
    state: "ولاية الخرطوم",
    city: "أم درمان (العرضة)",
    curriculum: "المنهج التكاملي القائم على حل المشكلات والتعليم الطبي الموجه لصحة الأم والطفل والتنمية الريفية.",
    highSchoolAdmissions: "مخصصة للطالبات فقط. قبول تنافسي وخاص متميز لشهادات السودان والمغتربين.",
    verifiedDoctors: 120,
    avgSmcScore: "95.0%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، ECFMG، WDOMS ومنظمات الأمم المتحدة.",
    highlights: "تأهيل قيادات نسائية رائدة في الطب العالمي والصحة العامة وبرامج الإغاثة الدولية."
  },
  {
    id: "MED-NATIONAL",
    code: "NAT-MED",
    nameAr: "كلية الطب — الجامعة الوطنية (السودان)",
    nameEn: "Faculty of Medicine, National University - Sudan",
    shortName: "طب الوطنية",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة الأولى (بنية تحتية متطورة ومحاكاة حديثة)",
    rankOrder: 28,
    estYear: 2005,
    state: "ولاية الخرطوم",
    city: "الخرطوم – سوبا / المعمورة",
    curriculum: "منهج تكاملي مدعوم بأحدث مراكز المحاكاة الإكلينيكية ومستشفى الجامعة الوطنية التعليمي.",
    highSchoolAdmissions: "قبول خاص / دولي للشهادة السودانية والشهادات المعادلة والمغتربين.",
    verifiedDoctors: 98,
    avgSmcScore: "94.6%",
    accreditationStatus: "معتمدة من المجلس الطبي، اتحاد الجامعات العربية، ECFMG، وWFME.",
    highlights: "مستشفى جامعي ضخم ومركز محاكاة سريرية ومعامل أبحاث ميكروبيولوجيا متقدمة."
  },
  {
    id: "MED-IUA",
    code: "IUA-MED",
    nameAr: "كلية الطب — جامعة إفريقيا العالمية",
    nameEn: "Faculty of Medicine, International University of Africa",
    shortName: "طب إفريقيا العالمية",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة الأولى (عمق إفريقي ودولي)",
    rankOrder: 29,
    estYear: 1996,
    state: "ولاية الخرطوم",
    city: "الخرطوم (الرياض)",
    curriculum: "المنهج الطبي التكاملي مع التدريب بمستشفى إفريقيا الجامعي والمستشفيات المعتمدة.",
    highSchoolAdmissions: "تستقبل طلاباً من أكثر من 70 دولة بجانب الطلاب السودانيين والمغتربين.",
    verifiedDoctors: 88,
    avgSmcScore: "93.7%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني، WDOMS، ECFMG.",
    highlights: "تنوع طلابي دولي فريد وتدريب سريري مكثف في طب المناطق الحارة والوافدين."
  },
  {
    id: "MED-IBNSINA",
    code: "ISU-MED",
    nameAr: "كلية الطب — جامعة ابن سينا",
    nameEn: "Faculty of Medicine, Ibn Sina University",
    shortName: "طب ابن سينا",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 30,
    estYear: 2000,
    state: "ولاية الخرطوم",
    city: "الخرطوم (الجريف / العمارات)",
    curriculum: "منهج تكاملي ومختبرات تخصصية بالتعاون مع مستشفى ابن سينا التخصصي لأمراض الجهاز الهضمي وزراعة الكلى.",
    highSchoolAdmissions: "قبول للشهادات السودانية والعربية والأجنبية.",
    verifiedDoctors: 75,
    avgSmcScore: "93.5%",
    accreditationStatus: "معتمدة من المجلس الطبي، WDOMS، ECFMG.",
    highlights: "ارتباط وثيق بكبار استشاريي الجراحة والباطنية وطب وجراحة الأسنان بالسودان."
  },
  {
    id: "MED-ALRAZI",
    code: "RAZ-MED",
    nameAr: "كلية الطب البشري — جامعة الرازي",
    nameEn: "Faculty of Medicine, Al-Razi University",
    shortName: "طب الرازي",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 31,
    estYear: 2001,
    state: "ولاية الخرطوم",
    city: "الخرطوم (الأزهري)",
    curriculum: "المنهج الطبي المتكامل والتدريب السريري بمستشفى الرازي الجامعي التعليمي ومستشفيات بحري والخرطوم.",
    highSchoolAdmissions: "قبول متاح للشهادة السودانية والشهادات العربية والأجنبية.",
    verifiedDoctors: 82,
    avgSmcScore: "93.0%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS وECFMG.",
    highlights: "مستشفى جامعي تعليمي نشط يخدم الكثافة السكانية جنوب الخرطوم."
  },
  {
    id: "MED-YARMOUK",
    code: "YAR-MED",
    nameAr: "كلية الطب — كلية اليرموك الجامعية",
    nameEn: "Faculty of Medicine, Al-Yarmouk University College",
    shortName: "طب اليرموك",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 32,
    estYear: 2007,
    state: "ولاية الخرطوم",
    city: "الخرطوم",
    curriculum: "المنهج المعتمد للعلوم الطبية الأساسية والتطبيق السريري بالمستشفيات المركزية.",
    highSchoolAdmissions: "قبول خاص معتمد من التعليم العالي.",
    verifiedDoctors: 54,
    avgSmcScore: "92.2%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "حضور قوي للخريجين في امتحانات الزمالات السريرية والتدريب التخصصي."
  },
  {
    id: "MED-NAHDA",
    code: "NAH-MED",
    nameAr: "كلية الطب والجراحة — كلية النهضة",
    nameEn: "Faculty of Medicine & Surgery, Al-Nahda College",
    shortName: "طب النهضة",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 33,
    estYear: 2014,
    state: "ولاية الخرطوم",
    city: "الخرطوم – امتداد الدرجة الثالثة (جنوب غرب مجمع كنار / تقاطع الصحافة شرق)",
    curriculum: "منهج طبي حديث بنظام الساعات المعتمدة ومعامل متطورة للعلوم الطبية الأساسية.",
    highSchoolAdmissions: "وجهة جاذبة للطلاب في الخرطوم وشمال بحري والمغتربين.",
    verifiedDoctors: 46,
    avgSmcScore: "92.5%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "نشاط بحثي ومجتمعي بارز وشراكات تدريبية إقليمية."
  },
  {
    id: "MED-HAYAT",
    code: "HAY-MED",
    nameAr: "كلية الطب — كلية الحياة الجامعية",
    nameEn: "Faculty of Medicine, Hayat University College",
    shortName: "طب الحياة",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 34,
    estYear: 2009,
    state: "ولاية الخرطوم",
    city: "الخرطوم",
    curriculum: "منهج تكاملي معتمد يركز على التدريب السريري السريع والمهارات الجراحية التمهيدية.",
    highSchoolAdmissions: "قبول تنافسي خاص للشهادات السودانية والعربية.",
    verifiedDoctors: 38,
    avgSmcScore: "91.7%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "تأهيل متميز في مهارات التشخيص المخبري والممارسة الطبية العامة."
  },
  {
    id: "MED-SIU",
    code: "SIU-MED",
    nameAr: "كلية الطب — جامعة السودان العالمية",
    nameEn: "Faculty of Medicine, Sudan International University",
    shortName: "طب السودان العالمية (SIU)",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 35,
    estYear: 2011,
    state: "ولاية الخرطوم",
    city: "الخرطوم (الأزهري)",
    curriculum: "المنهج الطبي التكاملي باللغة الإنجليزية والشراكات الدولية للتدريب والبحث.",
    highSchoolAdmissions: "قبول للطلاب السودانيين والوافدين والمغتربين.",
    verifiedDoctors: 42,
    avgSmcScore: "92.0%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "مجمع كليات طبية متكامل ومرافق دراسية حديثة."
  },
  {
    id: "MED-GARDEN",
    code: "GAR-MED",
    nameAr: "كلية الطب — جامعة غاردن سيتي",
    nameEn: "Faculty of Medicine, Garden City University",
    shortName: "طب غاردن سيتي",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 36,
    estYear: 2015,
    state: "ولاية الخرطوم",
    city: "الخرطوم (غاردن سيتي)",
    curriculum: "منهج طبي حديث بنظام الساعات والتعليم الإلكتروني الداعم.",
    highSchoolAdmissions: "قبول خاص للشهادة السودانية والشهادات الدولية.",
    verifiedDoctors: 28,
    avgSmcScore: "91.4%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني وWDOMS.",
    highlights: "بيئة أكاديمية متطورة وتقنيات تعليمية رقمية حديثة."
  },
  {
    id: "MED-NILEVALLEY",
    code: "NLV-MED",
    nameAr: "كلية الطب — جامعة وادي النيل",
    nameEn: "Faculty of Medicine, Nile Valley University",
    shortName: "طب وادي النيل (عطبرة)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى (صرح طبي عريق بولاية نهر النيل)",
    rankOrder: 37,
    estYear: 1990,
    state: "ولاية نهر النيل",
    city: "عطبرة",
    curriculum: "منهج سريري مكثف وتدريب بمستشفى عطبرة التعليمي ومستشفى السكة حديد العريق ومراكز الأورام.",
    highSchoolAdmissions: "نسب القبول: 88.5% – 91.5%.",
    verifiedDoctors: 84,
    avgSmcScore: "94.0%",
    accreditationStatus: "معتمدة من المجلس الطبي، WDOMS، ECFMG.",
    highlights: "تخريج أطباء ذوي مهارات جراحية وسريرية صلبة وتاريخ عريق بمدينة عطبرة."
  },
  {
    id: "MED-BAHRELGHAZAL",
    code: "BHG-MED",
    nameAr: "كلية الطب — جامعة بحر الغزال (بالخرطوم سابقاً)",
    nameEn: "College of Medicine, University of Bahr El Ghazal",
    shortName: "طب بحر الغزال",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى التاريخية",
    rankOrder: 38,
    estYear: 1991,
    state: "الخرطوم / بحر الغزال",
    city: "الخرطوم",
    curriculum: "المنهج الطبي القومي التكاملي وتدريب بمستشفيات الخرطوم وأم درمان الكبرى.",
    highSchoolAdmissions: "نسب القبول: 87.5% – 90.5%.",
    verifiedDoctors: 62,
    avgSmcScore: "92.9%",
    accreditationStatus: "معتمدة من المجلس الطبي وWDOMS.",
    highlights: "تاريخ أكاديمي عريق وأسرة تدريسية من كبار استشاريي الطب بالسودان."
  },
  {
    id: "MED-JUBA",
    code: "JUB-MED",
    nameAr: "كلية الطب — جامعة جوبا (التاريخية بالخرطوم)",
    nameEn: "College of Medicine, University of Juba",
    shortName: "طب جوبا (التاريخي)",
    type: "GOVERNMENT_FLAGSHIP",
    tierLabel: "الفئة الأولى التاريخية",
    rankOrder: 39,
    estYear: 1977,
    state: "ولاية الخرطوم",
    city: "الحرم الجامعي التأسيسي التاريخي - الخرطوم",
    curriculum: "المنهج البريطاني الموجه للتنمية الريفية والصحة العامة.",
    highSchoolAdmissions: "المرجع الأكاديمي التاريخي لآلاف الأطباء السودانيين والجنوبيين.",
    verifiedDoctors: 58,
    avgSmcScore: "93.5%",
    accreditationStatus: "معتمدة تاريخياً بـ WDOMS وECFMG وGMC.",
    highlights: "تاريخ مشترك شكل العمود الفقري للكوادر الطبية بالسودان وجنوب السودان."
  },
  {
    id: "MED-EMIRATES",
    code: "EMI-MED",
    nameAr: "كلية الطب — الكلية الإماراتية للعلوم والتكنولوجيا",
    nameEn: "Faculty of Medicine, Emirates College for Science & Technology",
    shortName: "طب الإماراتية",
    type: "PRIVATE_PIONEER",
    tierLabel: "الفئة الخاصة المعتمدة",
    rankOrder: 40,
    estYear: 2016,
    state: "ولاية الخرطوم",
    city: "الخرطوم",
    curriculum: "منهج طبي تكاملي ومعامل علوم أساسية ومحاكاة سريرية.",
    highSchoolAdmissions: "قبول خاص للشهادة السودانية والشهادات المعادلة.",
    verifiedDoctors: 20,
    avgSmcScore: "90.8%",
    accreditationStatus: "معتمدة من المجلس الطبي السوداني.",
    highlights: "تجهيزات معملية حديثة وتدريب سريري بالمستشفيات الكبرى."
  }
];

// Helper search and filter engine for the frontend
function getAllFaculties() {
  return SUDANESE_MEDICAL_FACULTIES;
}

function getFacultyById(id) {
  return SUDANESE_MEDICAL_FACULTIES.find(f => f.id === id || f.code === id);
}

function filterFaculties(category, query) {
  let list = SUDANESE_MEDICAL_FACULTIES;
  if (category && category !== 'ALL') {
    list = list.filter(f => f.type === category);
  }
  if (query && query.trim() !== '') {
    const q = query.trim().toLowerCase();
    list = list.filter(f => 
      f.nameAr.toLowerCase().includes(q) ||
      f.nameEn.toLowerCase().includes(q) ||
      f.shortName.toLowerCase().includes(q) ||
      f.city.toLowerCase().includes(q) ||
      f.state.toLowerCase().includes(q) ||
      f.code.toLowerCase().includes(q)
    );
  }
  return list;
}
